### ISSUE TITLE
Change way how we configure docker registries

### ISSUE THREAD

**Issue by riuvshin** [codenvy/codenvy#1027]
Today to configure custom docker registries and docker registries for aws ecr we require user to fill really tricky multi line property like:

```
$docker_registry_credentials = "registry1.url=my-private-registry1.com:5000
registry1.username=corp_user1
registry1.password=corp_pass1
registry2.url=my-private-registry2.com:5000
registry2.username=corp_user2
registry2.password=corp_pass2"
```

This approach will not work with codenvy in docker containers where we configure everything with ENV variables. 

My proposal is to configure only path to the file like:

```
$docker_registry_credentials = "/path/to/file.properties"
```

Where user will define his settings according to docs, then we check if user set path to his file we will volume mount this file to our server same as we are doing for all configs.

**Comment by riuvshin** [comment]
@mmorhun this is for you dude.

**Comment by benoitf** [comment]
using an external file may not be so simple for users

is it possible to use array properties like
docker.registry[0].url=my-private-registry1.com:5000
docker.registry[0].username=myUsername
docker.registry[0].password=myPass
docker.registry[1].url=another-private-registry1.com:6666
docker.registry[1].username=anotherUser
docker.registry[1].password=anotherPass

and then we can find a way to transform array ENV VARIABLES into properties

**Comment by garagatyi** [comment]
@riuvshin @TylerJewell which way is preferable for you guys?

**Comment by TylerJewell** [comment]
I would rather array environment properties instead of a file to be consistent for users.

**Comment by mmorhun** [comment]
IMO array looks a bit weird in properties, so I suggest use properties like this:
`docker.registry.auth.<user-defined-registry-name-1>.url=****`
`docker.registry.auth.<user-defined-registry-name-1>.username=****`
`docker.registry.auth.<user-defined-registry-name-1>.password=****`

**Comment by garagatyi** [comment]
@riuvshin I believe it is just a matter of naming of properties. 
@mmorhun can you confirm that we can implement both your proposal and Florent's?

**Comment by dmytro-ndp** [comment]
How about limitation of number of registries, for example, to 3? In this case we could avoid multi-line values at all. 
Also we could use special [array notation of variables in bash](http://tldp.org/LDP/Bash-Beginners-Guide/html/sect_10_02.html): `array=(value1 value2 ... value_n)`.
For example:
```
$ docker_registry_0=(url1 username1 password1)

$ echo ${docker_registry_0[0]}
> url1
$ echo ${docker_registry_0[1]}
> username1
$ echo ${docker_registry_0[2]}
> password1


$ docker_registry_1=(url2 username2 password2)

$ echo ${docker_registry_1[0]}
> url2
$ echo ${docker_registry_1[2]}
> password2
```

**Comment by mmorhun** [comment]
@garagatyi yes, we can.

**Comment by garagatyi** [comment]
Since property name should be compatible with shell variable naming suggestion from Florent won't work IMO. So @TylerJewell @riuvshin Please decide the format of configuration for that feature ASAP:
- property points to a separate file as roman suggested
- Mykola's suggestion

**Comment by benoitf** [comment]
well my point was mainly that we can still have properties instead of a single file
so if instead of 
`docker.registry[0].url=my-private-registry1.com:5000`

we have

`docker.registry.url.0=my-private-registry1.com:5000`  (or another format)

with an env variable `DOCKER_REGISTRY_URL_0="my-private-registry1.com:5000"` that's fine for me as well

**Comment by riuvshin** [comment]
Done. https://github.com/codenvy/codenvy/commit/6c7d43d380f700281f7b700517d6c987c484801a
We decided to use pipe "|" separator instead new line "\n" and in that case we are able to put string in single ENV VAR

**Comment by benoitf** [comment]
IMHO it's not user friendly to put several properties into only one

**Comment by TylerJewell** [comment]
This format does not work.  Let's discuss what other options we have if any.

**Comment by riuvshin** [comment]
this is the best we can do and most friendly way. problem that we don't know exact amount of credentials sets. with puppet we can assign only value to propery.  like ram.limit=<puppet injection value>
in our case we don't know amount of properties. So all I can do with that is consume whole set of props and parse them somehow. In fact what I did I've just changed parser to split on `|` instead of `\n`. this is better than multi line vars and much better force user to prepare whole file for us.
if we will limit credentials sets to 2 or 3 than we can define ENV var for each property.
for example like this:
```
CODENVY_DOCKER_REGISTRY_AWS_ECR_CREDENTIALS_ID_1=id_for_resgistry1
CODENVY_DOCKER_REGISTRY_AWS_ECR_CREDENTIALS_REGION_1=region_for_resgistry1
CODENVY_DOCKER_REGISTRY_AWS_ECR_CREDENTIALS_ACCESS_KEY_ID_1=access_key_id_for_resgistry1
CODENVY_DOCKER_REGISTRY_AWS_ECR_CREDENTIALS_SECRET_ACCESS_KEY_1=secret_access_key_for_resgistry1

```
same for _2


and same sets for AWS ECR

That means we will have 50+ extra ENV vars for in case of adding only few registries. which is crazy.

**Comment by TylerJewell** [comment]
I agree that having a lot of unnecessary environment variabes is kind of crazy. However, it is much more user friendly than having it as a single string separated by pipes.  I can guarantee that customers will make mistakes in typing the piped version, where they would not make mistakes in the format with 50 extra environment variables. 

So it's a trade off - and I think we have to error on the side of user friendliness over cleanliness.

**Comment by riuvshin** [comment]
Ok, what is the limit for amount of registries we support? 3 5 10? 
and for for each set we will add in `codenvy.env` all props so be ready that `codevy.evn` will be huge

**Comment by TylerJewell** [comment]
What if.....

We use env variables for the first one and then allow an optional file to list 2..n.

**Comment by gazarenkov** [comment]
The best option to me seems property file as a source (like proposed by Roman first time).

That is the example of a modular configuration.
Something like docker_registry.properties file copied to CHE_CONF_DIR

I'd wish such an approach to all the configuration instead of having huge one (manifest) for the whole configuration.

**Comment by TylerJewell** [comment]
I was a -1 on just having a file, because it adds complexity to the initial setup.  People put the wrong file name, cannot see what is in the file, etc.  We have a lot of issues with people not properly typing in configuration.

So my idea was to blend the two.  We have the first registry be configured as environment variables. This covers 99% of customers.  And then for the elite 1%, we give them an optional file that they can use for 2..n registries.

It's a nice balance of user friendly and scalable.

**Comment by gazarenkov** [comment]
File name does not matter, our container takes all the properties files from CHE_CONF_DIR.
But, correctly named it adds some structure, modularity of plain properties.
Also, file is going to be dedicated and considered to be small, so it is not that error prone.

Actually it is not opposite with env var approach, it is possible to have any dedicated component  provider with any rule (it may read/combine properties and|or env vars).
I love ability to override properties with env var but I would not overuse env var making an assumption that all the conf must be there.

**Comment by benoitf** [comment]
what is great with env variables is that any docker container can call another container very easily
with a file, then you need to do some volume mounting. With sibling containers you've to use host filesystem and not filesystem of the container so it becomes less "integrated".

Also with multiple files you always have users editing the wrong file. (even if for the guy that design the file or named the files it's "obvious", it's not for users.)

**Comment by TylerJewell** [comment]
@gazarenkov - i think you assume that users can get files names correctly and that we provide really smart messages when file names are mistyped, or if there is an error in the file itself.  When people have to add files, they will not be well commented, and if something goes wrong it is hard to know if it is because of a bad file name, or something that was improperly typed inside the file itself.

This is why I propose compromise - 1 registry in ENV file.  Everything else in a file.

**Comment by riuvshin** [comment]
Ok It seems I've found a way. I figured out how to take any amount of ENV vars by `contains` some key and propagate those ENV vars from `codenvy.env` to codenvy environment file which will used by codenvy tomcat, using this way  we don't need property files at all, we configure codenvy tomcat via it own ENV vars. So in that approach user will need only add to `codenvy.env` ENV vars like

```
CODENVY_DOCKER_REGISTRY_AWS_ECR_CREDENTIALS_ID_1=id_for_resgistry1
CODENVY_DOCKER_REGISTRY_AWS_ECR_CREDENTIALS_REGION_1=region_for_resgistry1
CODENVY_DOCKER_REGISTRY_AWS_ECR_CREDENTIALS_ACCESS_KEY_ID_1=access_key_id_for_resgistry1
CODENVY_DOCKER_REGISTRY_AWS_ECR_CREDENTIALS_SECRET_ACCESS_KEY_1=secret_access_key_for_resgistry1

CODENVY_DOCKER_REGISTRY_AWS_ECR_CREDENTIALS_ID_2=id_for_resgistry2
CODENVY_DOCKER_REGISTRY_AWS_ECR_CREDENTIALS_REGION_2=region_for_resgistry2
CODENVY_DOCKER_REGISTRY_AWS_ECR_CREDENTIALS_ACCESS_KEY_ID_2=access_key_id_for_resgistry2
CODENVY_DOCKER_REGISTRY_AWS_ECR_CREDENTIALS_SECRET_ACCESS_KEY_2=secret_access_key_for_resgistry2

```

I thought with puppet I can't do that but I figured out how with Ruby injections.

WDYT guys?

**Comment by benoitf** [comment]
@riuvshin would be nice for me
it's matching my latest proposal https://github.com/codenvy/codenvy/issues/1027#issuecomment-258086076

**Comment by gazarenkov** [comment]
Again, name of the file is not a mistake - it will work in any properties file (it can be saved in single file too, I just do not like it), it is the matter if configuration is well or bad structured but it does not impact on functionality.

I do not mind of solution @TylerJewell proposed, I mean that in general we have to be flexible with it, no sense to reject property files just because in some cases env variables are better.

@riuvshin sorry, but I am not a fun of huge configuration in one place, so I rather -1.

**Comment by TylerJewell** [comment]
I think this approach works gennady.  The user only adds env entries for registries they need.  So the env file stays clean.

**Comment by riuvshin** [comment]
@gazarenkov I understand your point and I agree with you that if you know what to do it is much easier to change existing configs directly in property files. But In current puppet based system and here in docker based way we use single file with all parameters that we allow to adjust for user due to many really valuable reasons, for example:

-  we always keep that file during upgrades and replace everything else which allow safely do refactorings and renames for prop names and etc.

- Single file for user that does not know whole system is much easier to operate in case of configuration changes and supporting documentation for this. (update docs for each property renames and refactoring will be big problem with out that.)

- that way allows us to have exactly same puppet modules code base (config templates) for different  environments like dev boxes, acceptances, stg and prod. they all using same templates but different manifests where all configuration set as needed for concrete env.

So I think my last proposal much better than what we have today, but I would keep working on that to make that system more flexible for future, for example use external property files or etc.

**Comment by gazarenkov** [comment]
Well, in any case user have to "know what to do" :)

I do not think that approach with one file technically worse or better than multi-file, I am not a puppet guru but pretty sure both is doable with comparable effort.

For codenvy.env file I actually see no big difference with our former approach where we had all the configuration in single properties file. 
It is totally OK and convenient until this file become huge.
The original conf system considered that by allowing keeping conf in many files. So, there is a choice - keeping all in one file or splitting to many files. Splitting strategy can be any - for example: by component, by functionality etc.
In any case it works. 

If the new concept keeps in mind such a flexibility (i.e. having one file is default but it does not make me to keep one file with millions lines) - it is fine. Otherwise - it would be really sad

**Comment by riuvshin** [comment]
Done.
changes:
https://github.com/eclipse/che/commit/d09dd3c5c43440aadc6c0424cf39585add1dec31
https://github.com/codenvy/codenvy/commit/e36836ea5179d80147bf91be9aed0c20327479a6

Aws credentials does not work yet due to: https://github.com/eclipse/che/issues/2454
