### ISSUE TITLE
Viewing all current build issues/errors?

### ISSUE THREAD

**Issue by bobpaige** [codenvy/codenvy#1046]
Is there a single place (like in Eclipse) that will display all current build errors?

**Reproduction Steps:**

1. build project from commandline (we use Gradle)
2. open each source file to see build errors

Many of the build errors I see while editing are related to my classpath (I missed a source directory or library). These don't appear in the terminal because Gradle finds everything. It is only in the editor I see the errors.

**Expected behavior:**

Some panel or listing of build errors that, when clicked, takes me to that error.

**Observed behavior:**

Errors are only visible when editing each file.

**Codenvy version:** 5.0.0-M5
**OS and version:** [Enter OS name and version here]

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy: [Yes / No]
Problem can be reliably reproduced: [Yes / No - it's random]

**Diagnostic bundle**
Execute the script on [this page](https://github.com/codenvy/codenvy/wiki/Support-Diagnostics) and post public link to the bundle here.

**Comment by TylerJewell** [comment]
Hi - we do not provide a single build view capability.  However, this is a capability that can develop over time.  I would take a look at our next step in the Roadmap (in the wiki) which outlines our vision for Intelligent commands.  That is our emphasis right now, and not necessarily adding these additional views.  Intelligent commands are needed as a pre-req to these sorts of advancements.

On some of these issues, I am going to close them, only because they are not currently in our roadmap, and we are working to try and keep our backlog of issues trimmed down.  It's not a reflection on the importance of the issue or whether we will do it in the future, just a technique for us to try and keep some sanity on a project that is getting a lot of traction :)

**Comment by bobpaige** [comment]
Took me a bit to find the roadmap :)

Any chance the output of an intelligent command could be persistent? I.e. I run a "build" command and it produces output that includes clickable links to errors within files? I can imagine this being more generally useful as well:
- run unit tests and display hypertext output of errors (Gradle Test already produces HTML output of errors, so maybe just viewing HTML within Codenvy would be good enough)
- output results of static analysis
- and obviously output build errors/warnings.

I can take this discussion to (https://github.com/eclipse/che/issues/2681) if you like, but thought I would start here first.

**Comment by TylerJewell** [comment]
I think that is a loaded question :)
1. Parsing output text for HTML and markdown.  This is not possible today, but understand hte need for it.  The editor windows, terminal window, and the command output window are three different systems, each with different mechanisms for input and output presentation.  So, I think it would be a longer term exercise for us to rationalize it so that we can use consistent mechanisms when scrolling data goes by.  

2. Interim, you can run commands directly in the terminal, and depending upon the shell that you have activated, you can get some gorgeous formatting there.  Granted, it's not part of the command, but it gets you there.

I think you can certainly redirect some of your commands into the intelligent commands epic, but I think the PM will designate it as a separate sort of topic.  The intelligent commands is about how to define a command and it gets selected for execution.  However, the presentation of the command is a bit different.  We have another issue #2151 which is about having parameterized input commands.  And having templatized output formatting seems to be similar to that.
