### ISSUE TITLE
Investigate KV storages for docker overlay networks

### ISSUE THREAD

**Issue by riuvshin** [codenvy/codenvy#1066]
needed for https://github.com/codenvy/infrastructure/issues/6
today we are using etcd as KV storage for docker overlay networks which due to some reasons cause performance degradation. Main goal of this issue is investigate other products like Consul, Zookeeper etc to replace etcd.

**Comment by skryzhny** [comment]
We can't reproduce problems on devbox or staging.
So we decided to update etcd to current version.
https://github.com/coreos/etcd/releases
If it will not fix our problems we will switch to zookeeper in docker:
`docker run --name codenvy-zookeeper --restart always -d -p 2181:2181 -v /var/lib/zookeeper/data:/data -v /var/lib/zookeeper/datalog:/datalog zookeeper`
Because of complexity of setup we don't considering usage of 'consul' at this time.

**Comment by skryzhny** [comment]
We found that versions of etcd and switching to zookeeper doesn't help us.
We filled another issues https://github.com/docker/swarm/issues/2614
https://github.com/docker/docker/issues/29756
