### ISSUE TITLE
Are there plans for Help to provide documentation?

### ISSUE THREAD

**Issue by chrisjj** [codenvy/codenvy#1102]
Currently it offers only:

![image](https://cloud.githubusercontent.com/assets/6157073/20026815/24f199b6-a2fa-11e6-89b2-8038136c1c5b.png)

**Comment by TylerJewell** [comment]
We do not have any plans right now. All of our docs are on README, and we will eventually embed them within the on-premises distribution.

**Comment by chrisjj** [comment]
Wow. With decisions like that, how you hope to compete with even the most primitive desktop IDE, I do not know.

**Comment by TylerJewell** [comment]
@chrisjj - because we do not really want to compete with IDEs.  Most of our value is in the server-side provisioning of workspaces, and we are increasingly working to support any IDE within the system. 

Developers already have dozens of very high quality IDEs. They don't have many great server-side workspace management solutions available.  It's virtually impossible to be great at both.

Please be a bit mindful that we have to keep the issues to a narrow list.  We do a lot of work to document all of the features in the docs, but sometimes the docs are split between che docs and codenvy docs. Our goal is to have the codenvy docs include symlinks to every che docs, and that way there is coverage for most features.

**Comment by chrisjj** [comment]
> Developers already have dozens of very high quality IDEs. 

The sure do. Meaning few will welcome the productivity loss upon switching to this "gorgeous Eclipse Che cloud IDE" having a UI that looks like a throwback to the 1990s.

**Comment by TylerJewell** [comment]
In the 5.x release line there is a utility called 'che mount' which provides two way synchronization of the /projects file system from within the workspace onto any  operating system. This allows you to use a desktop IDE against a hosted workspace.  We use a unison file sync with a fuse-based file system, which gives you a lot of fine grained control over exactly what is synchronized so the performance is pretty good.

**Comment by chrisjj** [comment]
Thanks.
