### ISSUE TITLE
Can not create a workspace snapshot

### ISSUE THREAD

**Issue by uboot** [codenvy/codenvy#1114]
Right-clicking a running workspace in the "Recent workspaces list" does not offer a function to create snapshot. "Stop" is the only entry in the pop-up menu. Did I miss a configuration step?

**Codenvy version:**
Version : 5.0.0-M6
Revision : 219dac87e4c15201

**OS and version:**
codenvy.io

**Comment by TylerJewell** [comment]
Stop automatically snapshots a workspace starting in M6.  Did you see something in the docs that shows "Snapshot"?  We removed the specific actions of snapshotting as it was redundant as people always want to do it with stopping the workspace.  If it's still in the docs, they need to be refreshed with the new behavior.

**Comment by eivantsov** [comment]
@TylerJewell why is it a blocker? 

@uboot is asking for a new feature - make it possible to snapshot a workspace from the context menu by right clicking a workspace in the recent workspaces tab.

@uboot you can snapshot a workspace by switching to an operations perspective (top right corner), in Machine menu.

**Comment by TylerJewell** [comment]
It is not a new enhancement request.  It is a feature that used to be there that was removed.  So this issue exists because there must be references in docs that encourage or instruct people to use that right click and they should be removed.  So this is a blocker docs issue.

**Comment by uboot** [comment]
@TylerJewell Well, I read it in the Che docs at https://eclipse-che.readme.io/docs/machines#section-machine-snapshot. This is probably the wrong place to look at.

@eivantsov Thanks for pointing out that snapshotting is possible in the operations perspective. I was not aware of that.

@TylerJewell and @eivantsov However, it seems to me that both ways (manual snapshot in operations and the implied automatic snapshot) do not work for me. If I install a package in the machine (e.g. `sudo apt-get install cmake`), the package is gone after restarting the workspace. Am I missing something fundamental here?

**Comment by TylerJewell** [comment]
That would be an indication that something else was wrong.  We changed the behavior of how snapshots work in M6 and deployed that into codenvy.io a couple weeks ago.  Before it required that users explicitly performed a snapshot in order to retain the state. But we realized that many users would never do that, so we changed it to auto-snapshot any time that a workspace is stopped.

Can you perhaps show us an animated gif of how you are restarting the workspace?  It is maybe a scenario where the snapshot is not being detected and used for the startup. When a workspace starts, we have a choice of using the saved snapshot or the original base image. It should always choose the snapshot by default.  And if you start in the IDE, i believe we give the user a choice.

**Comment by JamesDrummond** [comment]
@TylerJewell Does not snapshot when I stop the workspace manually on codenvy.io . To test I started a workspace, did "sudo touch /testing"(root directory not in the projects folder), then stopped workspace by `Workspaces > (click name of workspace) > Stop button`, started workspace again, and looked for file `sudo ls /` but it's missing.

**Comment by TylerJewell** [comment]
@ashumilova - is this a regression?

**Comment by ashumilova** [comment]
@TylerJewell @JamesDrummond the autosnapshotting is turned off on codenvy.io, that's why it doesn't work on workspace stopping.

**Comment by riuvshin** [comment]
@ashumilova you are right! Snapshot feature in codenvy always was manual procedure, because if we will enable auto snapshots in scale this will just kill our infra with huge IO. We've discussed this problem in a past few times. It is ok to have autosnapshot enabled on CHE where only one user can affect on the system but not in codenvy. Our tests showed us that with autosnapshots on hosted codenvy system can't survive, due to high IO this affects really badly on everything.

**Comment by bmicklea** [comment]
Docs are fixed. If you use the Machine > Snapshot command from the operations perspective the snapshotting works.

**Comment by JamesDrummond** [comment]
That is pretty hidden :) . I was looking for it before and couldn't find it. I add an image to the docs to help others locate it.
