### ISSUE TITLE
Starting workspace runtime failure and link "Download outputs" is not working link

### ISSUE THREAD

**Issue by larrytalley** [codenvy/codenvy#1119]
I have an on-premise Codenvy evaluation.  I make a new workspace with a custom stack that I specify myself via pasting in a Dockerfile. There is something wrong with my Dockerfile and the workspace fails to start, but, the error log is swept off the screen before I can read the last lines. A messagebox at the top of the screen says "Starting workspace runtime / Retrieving the stack's image and launching it" and there is a link with the link text "Download outputs", but, when I click on the link nothing happens.

This is not 100% reproducible. This happens to me almost every time, but, once in a while, the messages that come from failure are configured slightly differently, and then I can actually get a link that works. I don't know what makes the difference. But right now I'm getting the symptom consistently with a very simple Dockerfile (with a known error.)

FROM codenvy/ubuntu_jdk8
CMD ["bob", "-c", "bob"]

**Diagnostic bundle**
Execute the script on [this page](https://github.com/codenvy/codenvy/wiki/Support-Diagnostics

) and post public link to the bundle here.

**Comment by TylerJewell** [comment]
@ashumilova - this looks like it would either be with the IDE team or the plugin team - looks like something in the transition from dashboard into IDE while a bad Dockerfile is booting.

@larrytalley - thanks for reporting this issue.  One of the things that is coming in either M8 or M9 shortly is a way to test the build and run of a Dockerfile while in the dashboard before the IDE opens. So we are building Dockerfile and Composefile debugging into the stacks editor, so that you can avoid this particular issue.

**Comment by ashumilova** [comment]
@larrytalley tried to reproduce, have error message in console and popup:
![image](https://cloud.githubusercontent.com/assets/1611939/20131303/4b59d334-a665-11e6-96ce-dd8ba581a70b.png)

we will take it for further analyzing.

**Comment by ashumilova** [comment]
duplicates https://github.com/eclipse/che/issues/4830
