### ISSUE TITLE
Touch support for Web-IDE

### ISSUE THREAD

**Issue by javarch** [codenvy/codenvy#1129]
Hi Guys,

i tried to use the Web-IDE on touch-enabled devices (iPad, iPhone, Android, ...) and figured out, that there are some problems with the navigation (e.x. Opening a File in File-Explorer, ...). Are there any attempts to support these kind of devices in future?

Thx in advance!

**Comment by TylerJewell** [comment]
This would be an Eclipse Che enhancement that is required.  The core team doesn't have any plans to focus on mobile devices, though there are 100 or so comments + issues asking about this on Eclipse Che. Our position has been to wait and see if the community wanted to get engaged to issue pull requests that would allow for this.  Probably a couple engineers for a month or two to work through all of the items.

**Comment by spaceghost69** [comment]
I know of only 2 relatively minor changes needed to support iPad with Eclipse Che ATM:

1. Touch response when "clicking" on folders -- basically in the file navigation you cannot expand folders.  I believe this is one line of code change or so to enable the touch response.

2. Typing in the code editor does not register certain keys including sadly the space bar.  So basically all your words run together without spaces.  I have never seen this in other web apps, obviously you can enter text with spaces in most web forms.  My guess is the auto-complete is interfering with some keyboard keys and not returning the underlying keyboard event to Safari.

I have not tested with Opera or Chrome (yet) so perhaps these are issues related more to mobile Safari than iOS specifically.

Considering the likely small amount of work, and the 100 or so comments about this, I don't see why it is not addressed.  Enabling mobile workflow is obviously a big deal -- why tie folks to a desktop when the very core idea of this product is to free developers from platform dependence?  Otherwise just use Eclipse if you need desktop anyway.

My 2 cents.

**Comment by sdavi101010** [comment]
Piling on ... can't use it at all on my iPad and don't want to carry both iPad and laptop to Europe :-(
