### ISSUE TITLE
All bitnami stacks do not work on the nightly server 

### ISSUE THREAD

**Issue by artaleks9** [codenvy/codenvy#1271]
**Reproduction Steps:**
* Go to  the https://nightly.codenvy-stg.com
* Try to create a template project from any  bitnami stack in the stack library.

**Expected behavior:**
* The project should be created and opened in the IDE.

**Observed behavior:**
* The workspace agent does not start.

**Codenvy version:** 5.0.0-M8
**OS and version:** Ubuntu 14.04

**Additional information:**
* Problem can be reliably reproduced: Yes
* See the attachment:
![bitnami_stack](https://cloud.githubusercontent.com/assets/5408906/20829312/3fa49368-b884-11e6-9d68-aca153398f6f.png)

**Comment by riuvshin** [comment]
@garagatyi
this happens only on codenvy in docker I think it may be related to rsync agent

**Comment by riuvshin** [comment]
so we've found few issues with that
1) here https://github.com/codenvy/codenvy/blob/master/dockerfiles/init/modules/codenvy/templates/rsyncrestore.sh.erb#L4
https://github.com/codenvy/codenvy/blob/master/dockerfiles/init/modules/codenvy/templates/rsyncbackup.sh.erb#L4
we have hardcoded username `user` and if stack username is different ssh connection will fail. (for bitnami staks it is `bitnami` user) 
So we need to extract username for those scripts same way as we extract user ID.

2) due to some reasons rsync agent not able to install on some stacks. we still investigate what is going on here.

**Comment by garagatyi** [comment]
First problem is exactly what Roman described. Another one is that agent that installs rsync doesn't wait installation end and start sync restore workspace files. In bitnami images rsync is not installed and this operation takes more time, so restoring with rsync fails.
