### ISSUE TITLE
[Question]  Associate custom file extension with existing editor 

### ISSUE THREAD

**Issue by DardoTheMaster** [codenvy/codenvy#1405]
Hello, i have a project with .sqf files,and i'd like to associate them to an existing linting.

Is it possible to do this?

**Comment by eivantsov** [comment]
@DardoTheMaster there's no c linting in Eclipse Che which Codenvy is based on. Do you use codenvy.io or an On-Prem version?

**Comment by DardoTheMaster** [comment]
Err i'm on codenvy.io
Sorry didn't mean exactly C , I was wondering only how can I associate an unknown file extension to an existing linting rule.

**Comment by TylerJewell** [comment]
@DardoTheMaster - this is currently possible in Eclipse Che if you provide a customized extension and you are running the product yourself. Eclipse Che has not yet bubbled this sort of capability up into the editor preferences so that an end user can configure this without having to customize the product.  And Codenvy inherits from Che, so the behaviors are coupled.

One of the 2017 goals with Che is a lot of improvements around simplifying configuration of key bindings, file extensions to linters, and so on - things that vary by programming language, that need to become more dynamic.

**Comment by DardoTheMaster** [comment]
Understood , thank you.
