### ISSUE TITLE
Develop specification how can set of synchronised folders can be customised

### ISSUE THREAD

**Issue by skabashnyuk** [codenvy/codenvy#1518]
Right now we have ability to synchronise only one folder ```/projects``` the goal of this task is to develop specification how this ability can be customised and extended with a set of folders.

**Comment by TylerJewell** [comment]
Should we extend this to also include a way to exclude sub-folders within `/projects`, too?

**Comment by garagatyi** [comment]
@TylerJewell @skabashnyuk is it supposed to support that in dev machine only? Right now we have backup mechanism only for dev machine.

**Comment by skabashnyuk** [comment]
I think we can start with dev-machine and see how we stand.

**Comment by TylerJewell** [comment]
I think we start with that - and then expect as customers adopt more broadly, they'll tell us what else needs to be considered.  I think it's more likely that customers will want *portions* of their projects replicated to different containers.  "Please put module 1 on dev-machine and module 2 on db-machine".

**Comment by skabashnyuk** [comment]
I think because of this issue https://github.com/eclipse/che/issues/3054 we need to extend the scope of syncing to non-dev mashines too.

**Comment by TylerJewell** [comment]
Ahhhh yes you are right.

**Comment by garagatyi** [comment]
Do we need that for factories?

**Comment by TylerJewell** [comment]
I would assume that factories require it as well.  Factories are just a way to launch a workspace.  The sync is an attribute of the workspace at large.

**Comment by garagatyi** [comment]
Now we limit time of backup/restore process and not limit storage space. If we change backup mechanism to sync everything from folders chosen by user it is possible that:
- they can abuse our system by storing huge amount of information in our storage. It make a space for abusing our system accidentally by choosing wrong directories to backup.
- if they choose to save huge folders like .m2 our sync mechanism may not be able to backup it fully and data may be missing/corrupted.
- user unintentionally restores system files into container and broke it in a weird way that would be not really easy to debug. Workspace won't start ever in that case unless admin kills backup of user.
- user sync to much files in backup storage and workspace start will take hours. BTW since we have limits on longevity of restore it is not possible now, but in that case workspace may not start as in previous case because will interrupt restore process.    
Looks like we need consider ways of preventing these situation before allowing users to backup anything.

We were considering allowing user to use rsync syntax to add some folder into syncing, but found that it can be bad UX for users. Here is an example how to add folder `/mnt/some/thing/else/config` into backup:
```
--filter='+ /mnt'
--filter='+ /mnt/some'
--filter='+ /mnt/some/thing'
--filter='+ /mnt/some/thing/else'
--filter='+ /mnt/some/thing/else/config'
--filter='- /mnt/some/thing/else/*'
--filter='- /mnt/some/thing/*'
--filter='- /mnt/some/*'
--filter='- /mnt/*'
```
Order of rules is important. Other cases are even more complicated. So now we considering to allow user to choose which folders include/exclude. Then we will need to create these complex rsync rules in code.  
We also should ensure that user doesn't sync the same folders from different machines because in that case syncing of several machines can override backups unintentionally. 

Also we have doubts on how we should store data of workspaces. Now workspaces may have several environments and machines in them may differ. So considered several ways of storing data with respect of several workspace environments.
One of the options is to disallow user to sync similar folders in different machines of environment. So if one machine syncs `/mnt`, no other machine of workspace environment is allowed to sync this path.
Another option is to store backups of machines into separate folders with some IDs. In that case user will be able to choose which backup to use in which machine of each environment. Drawback of this solution is that we will need 2 sync processes for dev machine since projects backup is shared between environments of workspace.

**Comment by TylerJewell** [comment]
Those particular filters and rules would be too complicated to give to end users. So it violates the KISS principle and we would be better off not giving such flexibility.

We should consider studying unison sync with unison profiles. The syntax is easy to define and can be authored in a text file. This would be user-friendly in terms of being able to author, test, and edit such profile configurations.  We would then be allowed to add our profile "filters" which would add additional or restrict additional areas of the workspace.

**Comment by garagatyi** [comment]
I don't consider it as stable and reliable as rsync. I've read some bad reviews and development of it wasn't as long as rsync and already abandoned. BTW we are running rsync for some time and it worked great, unison is not tested in production by us.

**Comment by TylerJewell** [comment]
The syntax that you proposed is not going to work for end users.  So we will need a different vision for this as the proposed implementation is too complicated and ultimately will not be something we would give to customers.

**Comment by garagatyi** [comment]
We can provide user UX of choosing file/folder only. Hard stuff we can do on our side. Sorry if I wasn't clear on that. We are not going to let user use that syntax.

**Comment by TylerJewell** [comment]
1. I think if we do this, we should provide this in Che as well as Codenvy.
2. It matters to go into Che, becuase if we implement some sort of per-workspace GUI for managing this, then we would allow that GUI to work for long term storage with workspaces in Codenvy AND it should be the same GUI that we would apply for the CLI's sync mechanism.  Today, the sync mechanism does work ok (and is quite fast), but it requires end users to provide a unison profile for optimization which is a lot of hard work.  If we were to provide a GUI on what / how they are allowed to sync to long term storage, why wouldn't that be the same logic as what you would sync for desktop IDE?

**Comment by garagatyi** [comment]
This issue didn't say anything about points you've stated. 
I didn't consider neither syncing in Che nor syncing in desktop IDE use-case. Especially cross-platform.

**Comment by TylerJewell** [comment]
I am not broadening the scope because of the proposed implementation.  If we are going to start heading down this path, then we maybe need to think about implications to Che and also using desktop IDE synchronized to a ws.

**Comment by skabashnyuk** [comment]
@TylerJewell are you sure we need that Che? Running away from rsync can extend implementation for really big amount of time, months I  think.

**Comment by gazarenkov** [comment]
I see syncing as an internal mechanism needed for particular type of infrastructure (distributed) and particular type of machines (transient one, like container).
Which is Codenvy but not Che. 

I would *not* expose this as a feature for any type of machines and infrastructure or even to sync between infrastructures. 
Too difficult and IMO not needed as we do not consider our storage as a reliable, final persistence storage (for example we do encourage developers to use VCS)

**Comment by TylerJewell** [comment]
That argument is largely a technical one that describes the characteristics of certain internal mechanisms.

However, that does not describe the end user reality.  It is possible and likely common that an end user will have a workspace that needs to be both replicated to long term storage in codenvy and replicated to their desktop storage for use with a cloud ide.

In the Che case, the end user has no need for long term storage replication but they do have a need for desktop sync.

Whether it is a sync to one location or two, the point is that it makes sense to have a single syntax by which an end user defines what should be synchronized, and preferably a single underlying technology that implements that sync.

**Comment by gazarenkov** [comment]
Yes, of course, it is a technical reality.
We can imagine anything but I am talking about the things which we  need to make the system work.
It is a huge technical challenge to make reliable, automatic, end-user configured system which makes data replication anywhere.

**Comment by TylerJewell** [comment]
My point on the end user concern is a legitimate one.  Regardless of whether we have one synchronization lifecycle vs. two (long term storage vs. desktop sync), in either case we are thinking about exposing some syntax to the end user (or admin) which will let them configure what is included vs. excluded in the synchronization mechanism.

Isn't it a good thing for us to require that the "recipe" for defining inclusion / exclusion of the synchronization is common between the techniques?  I (and users) will not mind that the replications take place at different times or initiated by different systems.  But I think it would be important for long term flexibility that the recipe format used is identical in both scenarios.

**Comment by gazarenkov** [comment]
I am talking about ability to provide reliable mechanism/infrastructure for the syntax.

**Comment by TylerJewell** [comment]
I am indifferent to the implementation of the infrastructure.  My requirement is that we investigate how to have same syntax for infrastructure and desktop sync.  I would image users would use the same implementation technique for both, but the syntax in what they define should be identical.

**Comment by garagatyi** [comment]
Here is the spec I was working on last time:
1. Syncing of projects is separated from syncing of other machine file. So dev machine syncing involves 2 syncing processes in case user wants to store other files from dev machine.
2. As it is now syncing projects set files permissions in accordance with current user in dev machine.
3. Syncing of other files should preserve real files permissions.
4. As it is now if restoring of projects files fails due to timeout or another reason WS doesn't start at all.
5. Whether restoring of other files fails or succeeds WS starts.
6. By default all files except /projects in dev machine are excluded from syncing.
7. To start syncing of machine user should add property into WS model here https://github.com/eclipse/che/blob/master/core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/workspace/ExtendedMachine.java#L35
Name of the property is **sync.rsync.filter**.
Value of the property is string with inclusion/exclusion rules.
8. We are considering next syntax for inclusion/exclusion rules:
To include file/folder use
```
+ /mnt/include
```
To exclude
```
- /mnt/include/exclude
```
9. If some machine syncs folder/file /some/dir no other machine can syncs the same path or its sub-path.
10. API server should not allow to store WS where sync runes don't satisfy requirements, e.g. sync the same path in 2 machines.
11. We store synced folders in single folder that represents root of machines.
```
/mnt/folder1
/projects
/var/log/db
            /dev-machine
...
```
So db machine can sync **/mnt/folder1**, **/var/log/db**. And dev machine can sync **/projects**, **/var/log/dev-machine**.
These folders will be synced into machines by the same path.

12. We would want to mark this as experimental feature. If user sync some weird files like /bin or /lib container stability is questionable. So it is up-to-user to decide does it make sense to take risks of synchronization. 

Question that wasn't solved:
1. How can we limit storage of projects/other files to not let user abuse the system?
2. Do we want to support some other features in inclusion/exclusion rules syntax? How hard is that to implement usage of this rules with rsync? For example exclusion  of file by mask (*.log, temp-*) or exclusion of some file/folder name anywhere in the hierarchy of included folder (target/, *~, .DS_Store).

**Comment by TylerJewell** [comment]
@garagatyi - on this design, I believe it will be possible for multiple machines in a single workspace environment to have the same folder that needs to be sync'd.  For example, you may in the future want to have one of your /projects on one machine and a second /projects on a different macahine.  But in both cases, you'll need to sync /projects.  Another scenario may be that you are running a cluster of services and each node in the cluster has cluster data in a single folder, and the user wants to include the data from each node.

**Comment by garagatyi** [comment]
We don't have 2-way sync, so if you change file in machine 1 and then it is synced into backup then sync from machine 2 with the same file will revert content in backup storage.

**Comment by TylerJewell** [comment]
My comments were not about two way sync.  It was more about what happens if there are files with same path but different content on multiple machines and the user wants to include the same path for backup on each?

**Comment by garagatyi** [comment]
We decided that this would be trade off to simplicity

**Comment by TylerJewell** [comment]
I see this as likely disaster with customers.  And it will show up in the worst times and ways.  I agree it is simpler.  But likely when customer discovers this will be at worst time and way.

**Comment by gazarenkov** [comment]
The way we propose it is the easiest to implement. I.e. we can use same (tested for a long time) mechanism of backup storage almost "as is".
We consider that being well documented this compromise is quite reasonable and non-blocker to customer.
Because:
- We do not recommend it to be used for system sensitive (well known by operation system) paths. (it is too big responsibility, system may easily fail)
- Otherwise user have to be able to rename the folder
- It is very unlikely to use this for other than DEV machine
- Clustering is out of scope, it is the level of infrastructure. I.e. if rsync implementation is conceptually wrong for cluster-able infra it means it wont work correct even for our current non-configured solution. There are many questions for this case so I would not consider it at all.

My conclusion is: better apply proposed configuration sooner than later. In a case we will be able to overcome this internal limitation one day, it does not impact on configuration format and existed configuration.

**Comment by TylerJewell** [comment]
I am now confused by the nature of the conversation.  I am not sure what we
are trying to solve at this time, the objectives and its profit.

Can we hold a review meeting next Thursday while in Cherkasy?

Before we implement this, we need to make sure that we agree on the goal
and how it ties to other initiatives.


Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55

**Comment by gazarenkov** [comment]
I believe the goal is to be able to configure machine folders to continuous backup and on-start restore. We consider hosted (i.e. codenvy) environment only. 
I.e. what we currently do for /projects folder but also to be able to configure other folders.

**Comment by eivantsov** [comment]
In addition to that, backing up/restoring `/projects` folder causes some misunderstandings due to rsync scripts respecting gitignore file.

**Comment by gazarenkov** [comment]
Yes, we need remove respecting gitignore as well.

**Comment by TylerJewell** [comment]
I think we need a glossary of some terms.  It may be necessary for others to understand this.  I am reading the thread over a number of times, and it's not clear what is happening & why.

Project Folders: "/projects" - can contain 0..n projects
Machine Folders: All folders other than "/projects"

I think the rules for such a sync:
1. We should do this for Che and Codenvy at the same time. I don't see the value in only doing this for Codenvy.  We already have a number of scenarios where Che users are wanting to apply filters on what is saved to long term storage. The volume mount syntax is faster, but not configurable. So the value of the capability for che and codenvy are the same.

2. The syntax will allow different projects to be sync'd to different machines?

3. The syntax will allow Machine Folders to potentially be sync'd, but assume that they are not by default.

The property would best be configured as `che.sync.filter` and / or `codenvy.sync.filter`. The extra `rsync` attribute is probably not necessary.

**Comment by TylerJewell** [comment]
@garagatyi - if our only implementation for synchronized folders assumes k8s persistent volumes without rsync, does this specification need improvement?  I think it's still valid as we want to allow for customization.

**Comment by garagatyi** [comment]
Since technical aspects of syncing with k8s differ from syncing with rsync I do think that this issue should be closed. When we get k8s implementation we will be able to reconsider syncing mechanism and rules.

**Comment by TylerJewell** [comment]
Let's use different language.  "Syncing" mechanism implies something like rsync.  However, in k8s, we will only use persistent volumes mounted everywhere.  That is not a sync - it's just a definition of which project files are included or not.

**Comment by garagatyi** [comment]
I think it's enough for a user. Do we need more complicated things like actual syncing?

**Comment by TylerJewell** [comment]
The term "sync" generally means "copy from one location to another".  We will not be doing that in the default scenarios, so the term "syncing" is a misleading phrase to use.

**Comment by garagatyi** [comment]
Well then we don't need this issue. I'm sure we can't estimate due date for this issue now, so we can close it and come round with new solution when we ready

**Comment by gazarenkov** [comment]
+1  @garagatyi 

That is generalization of solution for problem we have for Swarm implementation.
Since it is out of scope for the time being and it makes no sense to plan/estimate it, I find it reasonable to close this issue
