### ISSUE TITLE
Custom Preview URL for a LAMP Workspace

### ISSUE THREAD

**Issue by munfaqqiha** [codenvy/codenvy#1529]
I am a codenvy's free member. 

As you knew, every time a LAMP workspace is booted up, the node of preview url is always comes up differently.

I try to set up a custom preview URL within its workspace config, [see here](http://pastebin.com/raw/pW8fiCW0), and it was successfully shown after the apache server is started, see in [this screenshot](https://s27.postimg.org/gty2u3wdv/codenvy.png).

This's important because all OAuth are need a redirect url. If the codenvy.io's preview URL does not change, then I do not need to make changes to an OAuth's account panel, such as on google, facebook, etc.

So, what's the exact value for a static codenvy.io url and its node that should be applied on my CNAME record ?. 

Thank you very much.

**Comment by TylerJewell** [comment]
Hi!  Our workspace preview URLs are dynamically generated and have their port numbers change on every boot sequence. We also have a 15 minute idle timeout for workspaces - this is because they are designed for development and not necessarily application hosting.

You can deploy eclipse Che with an always in workspace configuration so that when your application is deployed with a preview URL, the URL created will never change as long as the workspace is running.

**Comment by eivantsov** [comment]
@munfaqqiha have you figured out how to create a command with the right preview URL for your apache server?

**Comment by munfaqqiha** [comment]
@eivantsov : Not yet. Can you give me a complete step to do that ?. Thank you.

**Comment by shai200** [comment]
I am having a similar issue, but for me the servers tab completely disappeared
<img width="964" alt="screenshot 2017-01-19 19 36 09" src="https://cloud.githubusercontent.com/assets/25229562/22117993/b126e16a-de7e-11e6-910e-14c225712a45.png">

**Comment by TylerJewell** [comment]
Shai - we upgraded codenvy.io to 5.1 this morning.  That version removes the servers tab from the ide and places it in the user dashboard.  We haven't communicated the release notes yet but will soon.

**Comment by eivantsov** [comment]
Preview docs - http://www.eclipse.org/che/docs/ide/previews/index.html

Closing the issue.
