### ISSUE TITLE
Optimization of cli execution time for port open check

### ISSUE THREAD

**Issue by benoitf** [codenvy/codenvy#1550]
I've noticed using traces of all commands executed by the CLI that the check of opening port is taking a very long time (30s on my computer)

I've added
```
PS4='+$(date "+%T %N")\011 (${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): } '
set -x
```
at the top of CLI entrypoint.sh to get traces

Code is at
https://github.com/codenvy/codenvy/blob/5.1.0/dockerfiles/cli/scripts/cli.sh#L131-L163

Improvements could include :
- use of a batch command (so we can check in one docker container run all the ports)
- cache the result of an open port (see [1])
- allow to skip port open

[1] cache:
for example for port 80
we do
```
$(port_open 80 && echo "${GREEN}[AVAILABLE]${NC}" || echo "${RED}[ALREADY IN USE]${NC}") \n"
```

and few lines after
```if ! $(port_open 80)```which call again a new docker container

**Reproduction Steps:**

**Codenvy version:**    5.1.0

**OS and version:**    macOS sierra

**Docker version:** 1.12.6

**Comment by TylerJewell** [comment]
One issue seems to be that we haven't found a clean way to check a port once and then set a flag.  If you notice the port_open command, we run it twice and so it's a double task.  I thought we had found a solution, but the variable flag for the test and printout was not working in a combined macro command.

**Comment by TylerJewell** [comment]
BTW - in the branch for Che where we are adding in checks during preflight for open network connections, we have also added in the option of `--fast` to skip all preflight checks.  So this would be a way to skip port checking.

Previously I tried to author a single line which would do a `port_open && || ` as a batch set of commands.  But Bash does not seem to accept this.  So we should probably create a single method that performs a port_check, output, and interrupt all within a single method if possible.  The problem with interrupting in a single port check is that I wanted to run all of the preflight checks so that the end user can see all ports that are failing at one go instead of interrupting at the first port.

**Comment by benoitf** [comment]
thinking overnight I was thinking about the following pattern. (to keep the fact that end user should know each failing port and not the first one)

: we run a single docker run command with all port mapping like `-p 8080:8080 -p 9000:9000`

--> if it's a success (probably most of the time) we have a single execution (so we dramatically reduce the boot time) and then we can display OK for each ports.
--> if it's a failure, we get the port that is failing, we remove it from the list of port mapping and we execute again the command minor the failing port. And we display KO for the failed port. Then we iterate until we got success or until we do not have port to test

Success at first : fast while if port are taken, it may take some time as we will fail on each port but this shouldn't happen for a regular launch.

**Comment by TylerJewell** [comment]
Very clever!  I will try this in a branch today.
