### ISSUE TITLE
CLI stops zookeeper before codenvy and this prevents stopping workspaces

### ISSUE THREAD

**Issue by skryzhny** [codenvy/codenvy#1554]
When doing upgrade I noticed that docker had thrown lots of exceptions about inability to work correctly when stopping codenvy.
I think this is because we stoping zookeeper before codenvy and swarm containers.
It also may affect ability to synchronyse projects to backup locations and doing snapshots.

**Reproduction Steps:**

- Start codenvy.
- Start workspaces in codenvy, like 10.
- Start codenvy update.

**Codenvy version:**    5.1.0

**OS and version:**    Centos 7.2

**Docker version:** 1.12.5

**Comment by TylerJewell** [comment]
I think we have two choices here for cli implementation.  One is that we execute a container stop of each container manually so that we can dictate the order of stop.

Another is that we put zookeeper into a separate compose sequence in a different file so it has a different lifecycle.

**Comment by riuvshin** [comment]
I think it is possible to do with compose dependencies, Im checking this now.

**Comment by TylerJewell** [comment]
I was looking for that and it does not seem possible unless there is new feature.

**Comment by riuvshin** [comment]
we believe that depends on affect not only start but also reverse for stop

**Comment by skryzhny** [comment]
As workaround I may propose temporary solution how to stop it
- Run on every worksapace node simple docker container that just holds RAM so codenvy can't start new workspaces but able to correctly stop existing ones: `docker run -m 10000m busybox`
- Wait some time, like 10 minutes
- Stop codenvy container via docker, not CLI `docker stop codenvy_codenvy_1`

**Comment by riuvshin** [comment]
but even this will work with compose ordering this is more workaround. Normal solution should be some special admin service in our API which will initiate prepare to stop (initiate stop of all running workspaces, backup them, logout all users etc.) and once we are ready to stop we do stop in any order. This is super important because even if compose order is works we have time out for stop `5min` if we have running 1000 workspaces and on codenvy api stop we trying to stop all running workspaces and backup their projects, so there is a risk that codeny api will be stopped even in right order before all workspaces will be gracefully stopped and users may lose their code.

I think this is important stability issue.

how I see the possible flow
- admin perform CLI stop
- CLI execute special command to prepare for actual stop (stopping workspaces,logout users etc.)
- CLI make sure that codenvy is ready for stop
- CLI does stop of codenvy containers.


@skabashnyuk @TylerJewell @skryzhny @garagatyi @benoitf WDYT guys?

**Comment by benoitf** [comment]
I agree that we may need a more graceful stop than the pure "docker-compose" stop command.

**Comment by TylerJewell** [comment]
This is interesting topic because this came up with @skabashnyuk and another Che user in another thread.  The user wanted the ability to configure two types of stops (what we do now, which is timeout-driven) and another which is an orderly stop, which waits for all workspaces to be properly stopped (and snapped) before performing server shutdown.

**Comment by benoitf** [comment]
linking to https://github.com/eclipse/che/issues/3886

**Comment by skabashnyuk** [comment]
@TylerJewell @skryzhny  can we close this issue?

**Comment by TylerJewell** [comment]
Let's have @skryzhny confirm, but I believe this is resolved.

**Comment by riuvshin** [comment]
we can close this.
