### ISSUE TITLE
Can't upload a big file

### ISSUE THREAD

**Issue by kulsoommansoor** [codenvy/codenvy#1565]
I am unable to upload a 43MB jar file and I am getting an error saying the "entity is too large". Is there a size limit to how big files can be if you want to upload them? Or is it because I don't have enough space in my account?

**Reproduction Steps:**

**Codenvy version:**    5.1.0

**OS and version:**    

**Docker version:**    

**Codenvy cli.log output:**

**Comment by bmicklea** [comment]
@eivantsov is there a maximum upload size?  I think there is but I don't recall what it is...

**Comment by eivantsov** [comment]
I am unaware of size limitation, but having huge files with projects will result in workspace start failure due to backup and restore failures.

@kulsoommansoor you may want to push your file to a git repo and then re-import.

I am closing the issue since Codenvy provides code hosting, and storing sizable binaries or other files prevents workspaces from starting.
