### ISSUE TITLE
running CLI: Your admin has not accepted the license agreement.

### ISSUE THREAD

**Issue by carljmosca** [codenvy/codenvy#1576]
When running the CLI via docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /some/directory:/data codenvy/cli start

I cannot register a new user and the above message is displayed.

**Comment by TylerJewell** [comment]
Can you show the output of the startup of Codenvy.  We also need docker version, docker info, and OS information.

**Comment by TylerJewell** [comment]
@dmytro-ndp - please assist here

**Comment by carljmosca** [comment]
output from startup:
WARN: You are using CLI image version 'latest' which is set to '5.1.1'.
WARNING: No kernel memory limit support
INFO: Proxy: HTTP_PROXY=, HTTPS_PROXY=, NO_PROXY=*.local, 169.254/16
INFO: (codenvy cli): Checking network... (hint: '--fast' skips version, network, and nightly checks)
INFO: (codenvy cli): Loading cli...
INFO: (codenvy cli): Checking registry for version '5.1.1' images
INFO: (codenvy config): Generating codenvy configuration...
INFO: (codenvy config): Customizing docker-compose for running in a container
INFO: (codenvy start): Preflight checks
         port 80 (http):        [AVAILABLE] 
         port 443 (https):      [AVAILABLE] 
         port 2181 (zookeeper): [AVAILABLE] 
         port 5000 (registry):  [AVAILABLE] 
         port 23750 (socat):    [AVAILABLE] 
         port 23751 (swarm):    [AVAILABLE] 
         port 32001 (jmx):      [AVAILABLE] 
         port 32101 (jmx):      [AVAILABLE] 

INFO: (codenvy start): Starting containers...
INFO: (codenvy start): Services booting...
INFO: (codenvy start): Server logs at "docker logs -f codenvy_codenvy_1"
INFO: (codenvy start): Booted and reachable
INFO: (codenvy start): Ver: 5.1.1
INFO: (codenvy start): Use: http://localhost
INFO: (codenvy start): API: http://localhost/swagger

MacOS Sierra 10.12.2
Docker version 1.12.6, build 78d1802
Docker info:
Containers: 15
 Running: 12
 Paused: 0
 Stopped: 3
Images: 31
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 150
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null bridge host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.41-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.951 GiB
Name: moby
ID: JGKI:7QDW:OJQS:ZZM3:QL42:QFWH:GBL3:HG4Z:EY42:V7DO:YF2I:X5SA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 132
 Goroutines: 107
 System Time: 2017-01-20T20:00:44.161793858Z
 EventsListeners: 2
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
Insecure Registries:
 127.0.0.0/8

**Comment by TylerJewell** [comment]
You were not asked to enter the license agreement when it was starting?  Super odd - can you delete `/some/directory` and then rerun the CLI just to do an `docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /some/directory:/data codenvy/cli:5.1.1 init`.  It should ask you to accept the license.

**Comment by carljmosca** [comment]
I was asked the very first time I ran it but not on the subsequent attempts.  I will try again.

**Comment by TylerJewell** [comment]
Yeah, good - if you have been asked, that is clear.  But then when you login as `admin/password` the first time you are asked once more.  And that should clear the checks moving forward.

**Comment by carljmosca** [comment]
ah, gotcha

**Comment by TylerJewell** [comment]
Cool - glad you got into the system.

**Comment by carljmosca** [comment]
Me too, thanks for an awesome startup experience (I have installed it previously but that is the coolest, locally anyway).

**Comment by TylerJewell** [comment]
There are a lot of people that have put in 1000s of hours to make it do that.  Some crazy stuff going on - we have a white paper coming out on how we did it soon.

**Comment by carljmosca** [comment]
Nice, will look for it and put it to use.

**Comment by SkipperA** [comment]
I was not prompted for the licence agreement, however, my first installation was not fully successful because OSX apache server blocked port 80. I unloaded system apache and uninstalled codenvy with docker rmi -f codenvy/cli. Installed again, but was not promted for the licence. 

Is there a way to do a "solemn declaration" that I will legally comply or should try another dev. kit?

Long live the lawyers of IT companies!

**Comment by TylerJewell** [comment]
Interesting! @benoitf please investigate. When you log into the admin dashboard the first time there should be another license acceptance. We do this for those that choose to ignore the license check on the command line.

[Tyler Jewell - Contact Using Hop](http://GetHop.com/?_hmid=1494523722)

On May 11, 2017 at 17:24 GMT, SkipperA <notifications@github.com> wrote:

I was not prompted for the licence agreement, however, my first installation was not fully successful because OSX apache server blocked port 80. I unloaded system apache and uninstalled codenvy with docker rmi -f codenvy/cli. Installed again, but was not promted for the licence.

Is there a way to do a "solemn declaration" that I will legally comply or should try another dev. kit?

Long live the lawyers of IT companies!

**Comment by SkipperA** [comment]
SOLVED. I could do it on the dashboard. Sorry...

**Comment by benoitf** [comment]
OK so we can close the issue ?

**Comment by SkipperA** [comment]
Sure. Thanks,
Ferenc
2017. máj. 11. dátummal, 21:11 időpontban Florent BENOIT <notifications@github.com<mailto:notifications@github.com>> írta:


OK so we can close the issue ?
