### ISSUE TITLE
User cannot remove itself from own team

### ISSUE THREAD

**Issue by vzhukovskii** [codenvy/codenvy#1608]
Member lists allow to remove user from the team in which he is owner. At least remove button is enabled. Proper way will be to hide remove button from the team owner

![codenvy - dashboard - meeee32 2017-01-25 18-43-10](https://cloud.githubusercontent.com/assets/1968177/22299878/66868bd8-e32e-11e6-8157-4da80cfd9e2b.png)

**Comment by ashumilova** [comment]
@slemeur how to handle this situation on UI - we have several places for member removal - owners sections, delete button in row of team member item and bulk deletion. In some cases when there are few admins or team owners - it won't be obvious which one to disable in bulk operation or why owner delete button is disabled. My proposal is to process notification - to provide clear text why member cannot be removed, instead of existing one "Can't remove permissions because there is not any another user with permission 'setPermissions'"

**Comment by slemeur** [comment]
From my understanding of the issue reported by @vzhukovskii is more general: How can I leave a team I'm a member of?
I don't think we have handle this case at this moment - we need to add a small

Otherwise, about your question:
- Team member can only leave the team.
- Team admins and Team owner can manage members (remove, add)

**Comment by ashumilova** [comment]
@slemeur For team members I can add "Leave Team" button smth similar to "Delete account" section

**Comment by slemeur** [comment]
Good for me. Thanks

**Comment by ashumilova** [comment]
https://github.com/codenvy/codenvy/commit/3f67a5f0202b0ba92ec5a8ed93a1904057660b16
