### ISSUE TITLE
How to remote deploy ?

### ISSUE THREAD

**Issue by dataSQL** [codenvy/codenvy#1699]
[https://www.useloom.com/share/0b6ff3d0ea4811e687d9e9b8f47cdc1e](video review)
Hello, with the free account, is it possible to set up an Eclipse environment with the ability to deploy locally? and remotely to AWS Beanstalk having Tomcat?

I want to review JSON string conversions with another individual, is it possible to use the free account to accomplish this?

**Comment by adamparish** [comment]
Same question. I'm using Codenvy because I want to develop in the browser. My last hurdle is getting my code deployed to Google App Engine without downloading the Google Cloud Tools.  I found this great article from two years ago that describes a Deploy menu, but looks like that feature was removed. 

https://medium.com/google-cloud/cloud-in-your-cloud-afb4260cef61#.udbowsalq

**Comment by dataSQL** [comment]
Thank you Adam,  did you resolve it?

My hope is to be able to have Eclipse in the cloud that I may develop/deploy to remote server (AWS) PLUS invite other coders to review my existing code in a collaborative environment.

Have you found a SAAS that offers this solution?

Jon

**Comment by TylerJewell** [comment]
Yes, this is possible as you can install different solutions into your workspace.  And then you can create a command (which is just a process) that connects to your cloud for deployment.  It would be the same process that you use to install and use SDKs or CLIs on your localhost, only you can do it from within your workspace.  One example of that is the instructions for how to set up Google App Engine: https://www.eclipse.org/che/docs/tutorials/gae/index.html

**Comment by adamparish** [comment]
@TylerJewell I got this work. While I think a Deploy menu option would be super awesome, I went into terminal on the docker workspace and installed the Google Cloud SDK. You've got a good product here. With this knowledge, I can now dev/hack on a chromebook and that's awesome.

**Comment by TylerJewell** [comment]
@adamparish - that is great that you got it working.  We used to have a Deploy menu with integrations to all of the top PaaS systems, but it was a lot of work to maintain it. They all have different authentication mechanisms and would not provide any financial support in the maintenance of the plugins.  The problem was compounded by each of the PaaS vendors changing their APIs frequently.  We had 4 people full time maintaining those plugins for awhile and eventually just defaulted back into asking people to install each cloud's SDK natively.

You can create a custom stack so that you have exactly the tools and authentication keys built into any workspaces created from that stack.  That is what our enterprise customers do.

**Comment by adamparish** [comment]
IMHO, Google being so serious about Chromebooks should buy Codenvy or Cloud9 and make developing more streamline.

**Comment by TylerJewell** [comment]
Cloud9 was bought by AWS last year.  Nitrous.io went out of business. We are the only remaining independent with both a SaaS offering and software that can be installed on-premises, and we back the Eclipse Che project, which has a lot of the ecosystem behind it. We like the idea of staying independent as there are just not any great alternatives doing what we are doing.

Google is working on some of their own projects based upon Orion, but we think they will eventuallly come around and choose Che / Codenvy.
