### ISSUE TITLE
Respect dns options of a Docker daemon for workspaces

### ISSUE THREAD

**Issue by eivantsov** [codenvy/codenvy#1749]
If an On Prem DNS can be resolved since only a custom DNS server resolves it, there's no way a Codenvy workspace can inherit dns from Docker daemon options.

Steps to reproduce:

1. Configure Docker daemon to be using a custom DNS resolver
2. Restart Codenvy
3. Start a workspace.

**Comment by TylerJewell** [comment]
Is this a CLI improvement in that the CLI needs to detect the DNS and pass it to the codenvy server?  Or would the codenvy server handle this outside the CLI?

This is probably a Che issue too.

**Comment by eivantsov** [comment]
When a workspace is created we probably send an empty array for dns, thus overriding Docker daemon settings.

**Comment by TylerJewell** [comment]
Ok, if this is an issue for workspaces, then it's not a CLI issue.  It's an issue of how the Codenvy / Che server passes the DNS information into a workspace.

**Comment by eivantsov** [comment]
Yes, not a CLI issue.

2 solutions that I see:

1. Do not send an empty array for dns thus overriding docker daemon settings.
2. Have a property in codenvy.env for a custom dns resolver address.

**Comment by garagatyi** [comment]
It works in such a way because of custom dns resolution technique used in docker.
We need to fix Nginx and manually add resolver into container conf.
Workaround that probably would help right now is to use IP for codenvy master and docker nodes and set dns resolver into /etc/resolv.conf on each docker node host (Not in docker conf, on host where docker runs).
Fix from us would probably take couple of days.
