### ISSUE TITLE
Unexpected allert window after consuming a factory (regression)

### ISSUE THREAD

**Issue by musienko-maxim** [codenvy/codenvy#1767]
**Reproduction Steps:**
Sometimes after quick paste a factory in the browser we have problem like on screenshot:
![selection_023](https://cloud.githubusercontent.com/assets/1640058/22881085/8816bff2-f1ed-11e6-89f0-0b0df9580fb1.png). This one reproduces in the `CheckFactoryWithMultiModuleTest` and `LoginBySshTest` selenium tests.
**OS and version:**   Ubuntu 14 TLS, was reproduced on nightly server

**Comment by riuvshin** [comment]
@skabashnyuk @vparfonov this is potentially blocker for 5.3.0 release please take a look asap

**Comment by musienko-maxim** [comment]
This problem difficult to reproduce in manual mode.  this usually is reproduced in selenium tests (i think it happens because some actions is performed very fast)

**Comment by riuvshin** [comment]
we have tests that fails due to this issue we should not ignore it. if it is not possible to reproduce manually feel free to run single test to reproduce this and debug

**Comment by SkorikSergey** [comment]
**Steps to reproduce in manual mode:**
1. Go to codenvy.io;
2. Create a workspace and start any project;
3. In this browsers tab go to any other web page;
4. Back to the codenvi.io.

**Expected behavior:**
The IDE returns to previous state(see screenshot 1 for the Chrome Developer tools output).

**Observed behavior:**
A error message appears(see screenshot 2 for the Chrome Developer tools output).

![anim](https://cloud.githubusercontent.com/assets/7760565/23217553/5a99e400-f922-11e6-80c0-0ac817feeeb3.gif)

 № 1
![selection_006](https://cloud.githubusercontent.com/assets/7760565/23217524/40834728-f922-11e6-8d38-4eb67fddf700.png)
№ 2
![selection_005](https://cloud.githubusercontent.com/assets/7760565/23217532/4a9ab7d2-f922-11e6-9c5b-05757e43bf6e.png)

**Comment by musienko-maxim** [comment]
On latest version cannot reproduce
