### ISSUE TITLE
How to edit recipe for machine in stack?

### ISSUE THREAD

**Issue by asthomasdk** [codenvy/codenvy#1788]
How do you edit the recipe for an existing stack ? 

I am trying to create a new custom stack and trying to port my existing docker compose files to Codenvy/Che machines. I am adding new machines using the recipe editor. As soon as I save a machine, I can view the recipe for saved machines - but I cannot edit them. So if I need to change anything, I have to copy the recipe contents, delete the machine and re-add it. Not very practical or productive... 

I could be overlooking something on how to achieve this- but think I have looked everywhere.

**Reproduction Steps:**

**Codenvy version:**    5.2.2 on prem. 

**OS and version:**    RancherOS 0.7.1

**Docker version:** 1.12.3

I am using Chrome on Ubuntu Mate (Version 56.0.2924.87 (64-bit)) if that makes any difference.

**Comment by slemeur** [comment]
Hi @asthomasdk 

Agree, the experience for editing the machine's recipe in a stack is incorrect.
This problem has been identified in the following issue: https://github.com/eclipse/che/issues/3883 which is going to be fixed in the current sprint.

For the time being, if you want to edit the recipe, the only solution would be edit the raw stack's configuration in JSON in the following section:
![screen shot 2017-02-16 at 10 33 14](https://cloud.githubusercontent.com/assets/1636769/23015501/5abc8436-f433-11e6-82b8-f8085eb46da5.png)

**Comment by asthomasdk** [comment]
Thanks @slemeur!

I had actually overlooked that you could edit the raw config. This is a work-around for now. 

In the docs, the animated graphic makes it look like you can edit the recipe. So I was frantically looking for ways to do this ;-)
