### ISSUE TITLE
Factory URL not working on https://github.com/<account-name>/<project-name>/commit/<commit-ID>

### ISSUE THREAD

**Issue by kmaillet-arcane** [codenvy/codenvy#1911]
The factory url as described in [here](https://codenvy.io/docs/integration-guide/workspace-automation/index.html) doesn't work when the git "target" is a commit.

**Reproduction Steps:**
- Create a .codenvy.json in the root folder of my repository
- Use a factory url with https://codenvy.io/f?url=https://github.com/<account-name>/<project-name>/commit/<commit-ID>

**Expected Behavior:**
- The workspace is launched and the repository is cloned at that commit

**Observed Behavior:** 
- Error INVALID FACTORY URL

**Codenvy version:**    
5.4.1

**OS and version:** 
Mac OS Sierra 10.12.3

**Comment by eivantsov** [comment]
I think it is not supposed to work this way. A link with commit id does not help Factory service find .codenvy.json

@benoitf can elaborate

**Comment by slemeur** [comment]
Tested.

I confirm the issue:
According to the documentation this factoryURL should work: https://codenvy.io/f?url=https://github.com/che-samples/web-java-spring-petclinic/commits/master

**Comment by slemeur** [comment]
@kmaillet-arcane 
Could you try with URL format like this one:
https://codenvy.io/f?url=https://github.com/<repo>/tree/<branch-name>

**Comment by slemeur** [comment]
Documentation was confusing about the format to use in order to point to a particular branch.
Will be fixed by: https://github.com/codenvy/docs/pull/96

At this moment, URL factories allow the following options:
- `?url=https://github.com/eclipse/che`: to import master branch
- `?url=https://github.com/eclipse/che/tree/5.0.0` : to import 5.0.0 branch
- `?url=https://github.com/eclipse/che/tree/5.0.0/dashboard` : to import subfolder `dashboard` from 5.0.0 branch

We don't have options to point to a particular commitID from URL factories. (it would be possible in the future). 

Does it answer your question @kmaillet-arcane ?

**Comment by kmaillet-arcane** [comment]
Great thanks! 
It is very clear now
