### ISSUE TITLE
Losing some files

### ISSUE THREAD

**Issue by richtera** [codenvy/codenvy#2025]
**Reproduction Steps:**
Start/Stop/Start Workspace various times with snapshotting enables.
Unfortunately I don't know exactly how to reproduce it, but I randomly lost a few files which then showed up as "Deleted" in git. It's not related to the ".gitignores" as the other defect I had posted a long time ago. Checking them back out they will persist correctly. I am monitoring right now to see whether I can do something to reproduce this, but it happened twice already.

**Codenvy version:**    
5.4.1

**OS and version:**    
CoreOS

**Docker version:**    

**Codenvy cli.log output:**

**Comment by richtera** [comment]
Just upgraded to 5.6
Status of 3 of projects after workspace restart. The fourth project has no missing files. It might be related to the other defect maybe after all. Looking at these files they do match some of my .gitignore patterns but are force added. So maybe this is identical to #1134. This is really starting to be problematic. My .gitignore is such that I don't commit files I don't want, except in certain places. This kind of thing is happening in almost all my repos. So for examples it might be:

```
.gitignore:
   *.json
data/.gitignore:
   !sample.json
```

Or sample.json is just force added to the repo. Your system will delete sample.json since it matches the .gitignore. The curious thing is why does it do this after a snapshot/restore which is supposed to keep all my files.

```
Your branch is up-to-date with 'origin/dev'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    reactor/dynamic-run/.gitkeep
```

```
Your branch is ahead of 'origin/nancy' by 2 commits.
  (use "git push" to publish your local commits)
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    src/app/TakeTheChallenge/index.html
        deleted:    src/index.html
```

```
Your branch is up-to-date with 'origin/nancy'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    Test_data.json
        deleted:    affiliations.csv
        deleted:    affiliations.json
        deleted:    allAnswers_save.json
        deleted:    allLogins.json
        deleted:    allLogins_oa-curator.json
        deleted:    allLogins_oa-selfstudy-demo.json
        deleted:    allLogins_oa-selfstudy-dev.json
        deleted:    allLogins_selfstudy.json
        deleted:    allQuestions_save.json
        deleted:    allUsers_save.json
        deleted:    anneSimul/Practice1Standard.json
        deleted:    anneSimul/Practice2FocalImprovement.json
        deleted:    anneSimul/Resident1Awesome.json
        deleted:    anneSimul/Resident2Acceptable.json
        deleted:    anneSimul/Resident3Struggling.json
        deleted:    anneSimul/Resident4FocalWeakness.json
        deleted:    anneSimul/Resident5StrugglesWithHard.json
        deleted:    cme/package.json
        deleted:    demo-qs.csv
        deleted:    keywordsMap.csv
        deleted:    lib/oa-analytics/package.json
        deleted:    lib/roulette-wheel/package.json
        deleted:    nbcrna_questions.json
        deleted:    nbcrna_questions.xlsx
        deleted:    orderedTest.json
        deleted:    package.json
        deleted:    selfstudy-questions_map-export.json
        deleted:    selfstudy/firebase/selfstudy.json
        deleted:    selfstudy/package.json
        deleted:    synthetic.csv
        deleted:    v11/package.json
        deleted:    v11/server/package.json
```

I have no idea why these particular files and I definitely did not delete them.
I will monitor this more, but it's very strange.

**Comment by eivantsov** [comment]
@richtera project files are not snapshotted, they are restored and backed up with rsync, and rsync script respects .gitignore. So, everything that is in your .gitignore is ignored by backup/restore mechanism.

**Comment by richtera** [comment]
But if I make some modifications in my repo and then the workspace stops how are those modifications restored? That rsync gitignore thing is not making a lot of sense to me.

**Comment by eivantsov** [comment]
Everything is saved. But /projects folder is backed up differently. .gitignore is respected for workspace projects.

**Comment by richtera** [comment]
I don't think this is going to work for most people. If gitignore is not updated correctly people would lose any file that is mentioned in gitignore. For example I gitignore all my build files and I certainly don't want them deleted.

**Comment by eivantsov** [comment]
You have them in .gitignore on purpose, correct? We treat your project exactly the way you treat it as git project.

**Comment by richtera** [comment]
Well I guess that depends on what you agree the "purpose" is. I have things in .gitignore so they don't show up in git status and won't be committed. Many of these files are manually put into the repository while I work on it. So they are important files while working but should just not get committed.

**Comment by TylerJewell** [comment]
Our basic premise is that anything in /projects is synchronized to a long
term backup storage.  We are working on utilities that will give admins (or
users) fine-grained controls over what exactly is part of that offline
sync.  We think of this as the project's that need extra attention, and
also things that should be injected into a workspace after it's runtime is
activated.  Handling the projects as a second step also has benefits
because in the future parts of projects may need different injection rules
for different workspace runtimes, such as having compose services where
each container gets a subset of the project tree.

This means that anything that is not part of the standard project tree is
treated as part of the runtime, and it's backup can be addressed through
snapshotting of the image when it is stopped. And this is done
automatically as a default, but can be overridden by admins or end users,
too.


Tyler Jewell // CEO // tyler@​codenvy.​com // 978.884.5355

**Comment by richtera** [comment]
Ok then we agree on which files should be in the backstore versus the snapshot.

Any file that's part of the repo should be rsync'd to the back store and any file that's not part of the repo should end up in the snapshot.

My though is that rsync's evaluation of .gitignore is incomplete and doesn't seem to implement the "!" operator. Maybe it would be better to use "git ls-files" as the list of files inside of the repo. That way if a future version of git implements new syntax in .gitignore or .gitattributes you would not need to rely on rsync to catch up implementing such. I have tried to cleanup some of my .gitignore files but it's not possible in some instances.

For example:
I have a config folder which contains a "default.yaml" file to setup the schema for the settings file. Any other *.yaml file should not be part of the repo so the rule is:
```
*.yaml
!default.yaml
```
Without knowing each variation of config yaml file it's not possible to write this rule.
I guess I could limit it to only support
```
production.yaml
production-*.yaml
development.yaml
development-*.yaml
```
but sometimes there are custom NODE_ENV versions I use which I still don't want to commit.
In many other repos I configure to exclude *.log files everywhere and sometime I commit log files inside of a folder with sample data. So there are many occurrences of this kind of pattern.

In addition sometimes we use "git add -f" to add a file which is inside of the .gitignore pattern because it's a special file and we don't usually bother to adjust the .gitignore pattern at all.

**Comment by eivantsov** [comment]
@richtera @TylerJewell the reason behind respecting `.gitignore` is avoiding backing up and restoring binaries and other build artifacts and project dependencies that can be huge for sizable projects. With the current rsync based implementation and backup/restore timeout, dealing with huge files is a big risk of potential failure, especially with a multi node installation.

@richtera you can however, tweak existing scripts to achieve behavior you need. You can edit `/instance/config/codenvy/conf/rsyncrestore.sh` and `/instance/config/codenvy/conf/rsyncbackup.sh`, namely:

```
rsync ${RSYNC_OPTIONS} \
      --rsh="ssh ${SSH_OPTIONS}" \
      --rsync-path="${RSYNC_COMMAND}" \
      --include='.codenvy/' --filter=':- .gitignore' \
      ${SRC_FOLDER} ${DST_HOST}:${DST_FOLDER}
```
 
Modify or remove `--filter`. There's no need to restart Codenvy, since this script is mounted into `codenvy` container.

**Comment by TylerJewell** [comment]
If you follow @eivantsov's advice on modifying the scripts in the /instance
folder, you will not be able to use the CLI any more. The CLI (by design)
overwrites the configuration in /instance on every start of the system.
This is how we guarantee mutability of the configuration itself. The CLI
reads your configuration and then sets up an OS-specific configuration with
files generated by puppet, overwriting any configuration files that may
exist in the /instance folder already.

So - beware of this limitation. We are debating - somewhat over a lenght of
time, a different implementation which offers finer-grained controls over
what is included in the synchronization mechanism on this thread -
https://github.com/codenvy/codenvy/issues/1518#issuecomment-291189769


Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55

**Comment by eivantsov** [comment]
@richtera yes, I forgot to mention that when you restart Codenvy, these changes are overwritten, so you may want to create a simple script that will `cp` a custom script to its permanent location in `/instance` folder.

**Comment by eivantsov** [comment]
@TylerJewell what are we going to do about respecting `.gitignore`? Removing it from rsync scripts is a 2 min assignment but do we really want to do that?

**Comment by TylerJewell** [comment]
I believe the proper handling of .gitignore is covered by the specification
that @garagtyi had started. We should make sure that the specification
reflects the proper requirements and then track that for ultimate
resolution.  I think, generally, that if we have user-level overrides for
synchronization then those apply and stuff in .gitignore does not matter.


Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55

**Comment by eivantsov** [comment]
@TylerJewell is there an issue that we can link to this one?

**Comment by TylerJewell** [comment]
Yes - let's use this issue as tracking issue.  https://github.com/codenvy/codenvy/issues/1518
