### ISSUE TITLE
Unable to run Simple Hello World!

### ISSUE THREAD

**Issue by smiske** [codenvy/codenvy#2037]
**Reproduction Steps:** The RUN dropdown menu is mainly grayed out with no way to run my first simple test program of "Hello World!"  I can build the code, just cant figure out how to run it.  I looked in the command pallet and I do not see how to create a run command

**Codenvy version:**  5.6.0

**OS and version:** 
![2017-04-03](https://cloud.githubusercontent.com/assets/5221929/24629373/6b074532-187e-11e7-9248-ca2dacfa8e86.png)
Win 10    

**Docker version:**    

**Codenvy cli.log output:**

**Comment by slemeur** [comment]
Hi @smiske.

Click on the "run" button in the toolbar - it should propose you to "Create and start command".

Otherwise, on the left of your IDE, bellow the "Projects" explorer panel, you have the "Commands" explorer panel. 
![6b074532-187e-11e7-9248-ca2dacfa8e86](https://cloud.githubusercontent.com/assets/1636769/24629558/b72c3d6a-18b9-11e7-8f6b-e6d4d226b0d6.png)

You can find documentation here:
https://codenvy.io/docs/user-guide/commands/index.html#managing-commands

Alternatively, to make it easier to find how to add a new command we will:
- add a "Create and start command" when you click on the main toolbar controller.
- add from the "Run" menu an entry for "Edit Commands".
