### ISSUE TITLE
Custom cli package management mishandled by workstation

### ISSUE THREAD

**Issue by janat08** [codenvy/codenvy#2119]
I installed a cli from this repository: https://github.com/reactioncommerce/reaction
I dont know how it deals with dependencies, but they're gone on workstation restart. The peculiar thing is that you then only have to install those dependencies through npm (for Node.js), rather than through the same cli, at which point the package dependencies get gone again after restart.

**Comment by TylerJewell** [comment]
Hi @janat08 - please check the .gitignore after the clone. It is expected behavior right now that when we snapshot a workspace (for saving) that we exclude the contents of the .gitignore. We are doing this for saving and performance purposes (imagine snapshotting a 2 GB maven repo).  We know that this is causing some problems (there was another issue on this earlier today) and we are working on a refactoring that will make it user configurable to determine which components are part of a snapshot vs. those that are not.

Is this the issue you see?

**Comment by janat08** [comment]
It would appear. It's a docker image too. Gives me errors now, for touching .gitignore I imagine.
