### ISSUE TITLE
Real-time collaboration

### ISSUE THREAD

**Issue by st0de** [codenvy/codenvy#2226]
Hi!

I would like to know how to collaborate with developper in real-time on a project. I mean like Google Docs or Cloud9 where you see the cursor of your teamate. 

As it it mentionned here: [https://blog.codenvy.com/march-release-real-time-collaboration-editor-themes-and-code-folding-e4620f42cbf1](url)

I found docs on how to create team and share projects: [https://codenvy.com/docs/user-guide/teams/index.html](url)

But there's no documentation on how to start real-time collaboration.

Thank you!

**Comment by TylerJewell** [comment]
Hi.  We support multiple users in a single workspace. But we do not currently support multi-cursor editing where multiple users see what other users are doing at the same time.  Systems like cloud9 use hosted Firebase APIs for coordinating such activities. But since our system ships on premises and works behind the firewall, the libraries for implementing multi-cursor editing scalably are not strong enough yet.  So we provide multi-user access to a workspace, with eventual updates to the screen.

**Comment by st0de** [comment]
Thank you
