### ISSUE TITLE
There is an error message when create a workspace or a team

### ISSUE THREAD

**Issue by SkorikSergey** [codenvy/codenvy#2231]
**Reproduction Steps:**
1. Try to create a new team or a workspace
2. Click the **Save** button

**Observed behavior:**
There is an error message 

**Server location:** https://nightly.codenvy-stg.com, https://nightly-onprem.codenvy-stg.com

**Additional information:**
The problem is reproduced rarely.

Creating a workspace:
![ws_creating](https://cloud.githubusercontent.com/assets/7760565/26442060/a6f07b00-413b-11e7-9df7-274c1f2ec688.gif)
Creating a team:
![team_creating](https://cloud.githubusercontent.com/assets/7760565/26442086/b753ca60-413b-11e7-8475-3a55e0c0fb7a.gif)

**Comment by evoevodin** [comment]
Thank you @SkorikSergey.

It happens because of the CSRF protection implementation approach which i implemented for dashboard, it supposes that first get request/response forwards the first modification(POST, PUT, DELETE) request, but it seems that it is not true, automation test sometimes might send a modification request before GET request response is received and processed.

The solution would be to use on demand X-CSRF-Token fetching when the first modification request is sent
- modification request is about to be sent
- go and fetch X-CSRF-Token. It can be fetched within any GET request, more details are [here](https://github.com/codenvy/codenvy/pull/2213)
- add X-CSRF-Token header to original modification request

The example of such interceptor is [AddMachineTokenToUrlInterceptor](https://github.com/codenvy/codenvy/blob/b2dca395aafe68c174c7754c4b8d3c2584f8424e/dashboard/src/app/index.module.ts#L168)
