### ISSUE TITLE
Cannot run Java Swing GUI in Codenvy

### ISSUE THREAD

**Issue by veepipi** [codenvy/codenvy#2408]
**Reproduction Steps:**
1. I have imported this program: https://github.com/codenvy-templates/desktop-swing-java-basic
(Save as project Test_Jswing)
2. Created a maven command under Build with the following information:
CMD: mvn clean install -f ${current.project.path}
Preview URL: http://${server.port.8080}/${current.project.relpath}
Project is turned ON.
3. Run the maven command in # 2.
Generated URL: http://node26.codenvy.io:34587//Test_Jswing/target/desktop-swing-java-basic.jar
4. In the Terminal, I run command 
java -jar Test_Jswing/target/desktop-swing-java-basic.jar

Error is shown:
Exception in thread "main" java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it..

**Codenvy version: 5.17.0**  

The stack that I'm using is java-centos-mysql. I need MYSQL for future use. 

For your help. Thank you!

**Comment by eivantsov** [comment]
@veepipi perhaps, this link will help http://www.eclipse.org/che/docs/tutorials/swing/index.html

**Comment by gotic3n** [comment]
I am having the same issue. i followed the tutorial in the link but it doesnt work for me. 
i cant open the webbrowser x11 window. i tried putting the preview address in vnc client and it doesnt work either. 

i creader the workspace, i created the maven command and imported the swing app from github. it compiled fine. then i press the preview http://node27.codenvy.io:32937//desktop-swing-java-basic link in chrome and it says 

This site can’t be reached

node27.codenvy.io refused to connect.
Try:
Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

is there something extra that i i need to do?

i run
user@d7d078cb3acf:/projects/desktop-swing-java-basic/target$  java -jar desktop-swing-java-basic.jar
Exception in thread "main" java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:207)
        at java.awt.Window.<init>(Window.java:536)
        at java.awt.Frame.<init>(Frame.java:420)
        at java.awt.Frame.<init>(Frame.java:385)
        at javax.swing.JFrame.<init>(JFrame.java:189)
        at com.codenvy.example.swing.Hello.main(Hello.java:17)

**Comment by eivantsov** [comment]
Try using `eclipse/x11_vnc` image

![image](https://user-images.githubusercontent.com/5337267/31280181-3732f076-aab4-11e7-8791-3c23b4baaced.png)

![image](https://user-images.githubusercontent.com/5337267/31280198-438b569c-aab4-11e7-9d5b-6ea27fbe9be6.png)

**Comment by gotic3n** [comment]
Thank you for the fast response. i built it using the new image and from your pictures i got it working
 some notes for anyone struggling with the same issues.

It turns out i wasn't following the tutorial as i should.
the key was the preview url.

i created a default maven command which had the clean install command but i kept the default ${server.port.8080} preview url. 

this is why it didnt work it seems. 

you need to scroll down and change the server to ${server.port.6080}

it seems the first guy in this post probably had similar issue with the port.

then it will pop up the novnc and you can rightclick and get a terminal and navigate the terminal in the desktop to the jar folder and execute.

i went back to the workspace i build using the tutorial image and changed the port to 6080 and it worked fine as well. also remember to have" ${server.port.6080} " only no path or anything. that also screws it up.
