### ISSUE TITLE
Polymer Preview not accessible

### ISSUE THREAD

**Issue by hedler** [codenvy/codenvy#2486]
The Problem is that there is no tutorial how to configure codenvy correct for google polymer.

**Reproduction Steps:**
1. Create Workspace based on recipe eclipse/node
2. sudo npm install -g polymer-cli
3. sudo npm install -g bower
4. mkdir my-app
5. cd my-app
6. polymer init polymer-2-starter-kit
7. Create Run Command:
        Run Command:  "cd ${current.project.path} && polymer serve --port 3000"
        Preview URL: "http://${server.port.3000}"
8. Run
9. Under the preview URL is no polymer app accessible

**Codenvy version:**    Version :5.18.0Revision :44970264fd881111 Build Time :2017-09-20 11:00:16

**OS and version:**    Ubuntu 14.04

**Codenvy cli.log output:**  empty

**Comment by eivantsov** [comment]
@hedler Since port 3000 is exposed in Node image, I can suggest that you unbind your app from localhost. I would try adding and extra argument like `--hostname 0.0.0.0`. That should help. The problem here is that by default the server accepts requests from localhost only. Since the proccess is running in a container, and when you hit the preview url, you are forwarded into a container. Thus, you access it from outside.

**Comment by hedler** [comment]
Thank you, it works.

Run Command: "cd ${current.project.path} && polymer serve --port 3000 --hostname 0.0.0.0"
Preview URL: "http://${server.port.3000}"

**Comment by eivantsov** [comment]
I'm glad it worked for you. Closing the issue.
