### ISSUE TITLE
OAuth with github appears to be broken

### ISSUE THREAD

**Issue by mpouttuclarke** [codenvy/codenvy#357]
When I log into Codenvy using Github I get an auth failure when setting up a project to a private repo.  Please see attached screen shot.
<img width="1066" alt="screen shot 2016-07-07 at 12 54 23 pm" src="https://cloud.githubusercontent.com/assets/353125/16667607/3f3ccdc0-4442-11e6-8475-05d0c3f9ff67.png">

**Comment by mpouttuclarke** [comment]
I tried clearing all my cookies from codenvy and it did *not* fix the issue.  Now trying to clear github cookies as well.

**Comment by mpouttuclarke** [comment]
I cleared both github and codenvy cookies and it is still the same error message.

**Comment by TylerJewell** [comment]
What happens if you create a blank workspace and then after the IDE is opened, creating the project from within the workspace using the IDE menu?  I am wondering is you still get an oauth or private key failure.

**Comment by mpouttuclarke** [comment]
I'll give it a try, thanks Tyler

**Comment by mpouttuclarke** [comment]
No dice, same error.  It boots the new workspace but when I try to add a project to the workspace it fails immediately with the OAuth error attached.  The logs contain literally nothing except:

Cloning into '/projects/hadoop-dev'...

**Comment by mpouttuclarke** [comment]
I'm going to try from one of the canned stacks to see if that's the issue.  I'm using a custom stack right now.

**Comment by mpouttuclarke** [comment]
Even with the vanilla Java stack it fails so it's not the custom Hadoop stack causing the issue.

**Comment by TylerJewell** [comment]
Huh.  It is working for me.  Just to confirm - this does not happen with public repos, just private?

**Comment by mpouttuclarke** [comment]
Just private, exactly.  With public repos it works fine

**Comment by TylerJewell** [comment]
@ddementieva - she will have better answers than me.

**Comment by ddementieva** [comment]
Have you generated SSH key for Github? 

Currently it should be done directly in the IDE, so you can simply create a workspace with Hadoop image, open it in the IDE, go to the Profile > Preferences > SSH > VCS menu and click `Generate key and upload it to Github` button. New SSH key for github.com will appear in the list. 

After that try to import your project with Workspace > Import Project... option.

**Comment by eivantsov** [comment]
@mpouttuclarke Here's a link that may help - https://eclipse-che.readme.io/docs/git#section-github although it's Che docs and you do not need to add anything in properties file.

The problem is though that you have access to ssh key management only having started a workspace. So, I suggest you start an empty workspace, go to Profile > Preferences and click the octocat button.

This should fix it for you.

**Comment by thaddaeus** [comment]
Having the same issue (though not in beta as the OP apperas to have been). Oauth looked good, ended up being the ssh key.  This was already generated and pushed to github, it appears to be  needed again.  

In an existing project: Window > Preferences > SSH Keystore. Then click the octocat button in lower right and everything worked again and normal. 

Not sure of root cause though. This workspace was created about two weeks ago along with the repo and had no issues until I pushed changes last night.

**Comment by eivantsov** [comment]
@mpouttuclarke  so what you are saying is that you had to re-generate SSH key for GitHub?

**Comment by thaddaeus** [comment]
@eivantsov Specifically I just clicked the button in the lower right that says it generates and pushes to gitihub - I did not compare the before and after keys on Codenvy so I'm not certain.   I use https rather than ssh to link to my repo as well.

**Comment by eivantsov** [comment]
@thaddaeus do you still encounter this issue?

**Comment by thaddaeus** [comment]
@eivantsov I have not had this issue again
