### ISSUE TITLE
Create list of all entries that connected to user

### ISSUE THREAD

**Issue by ashumilova** [codenvy/codenvy#387]
Before we can actually delete user we need to know what to do with all stuff produced by user. To know that we need to make sure we know about all entities what user can have.
For example
- Source files
- Factories 
- Recipe

As a result of this issues we need to initiate discussion what to do with this entries: keep, delete, update somehow

**Comment by TylerJewell** [comment]
Our policy will be to delete everything *created* by this user. Sharing policies do not matter - we will destroy all items. We should present to the user the list of items that they have created and maybe we even show them which resources are shared with others so that they know the impact they may create.

**Comment by skabashnyuk** [comment]
0. User itself
1. Profile 
2. Preferences
3. Source files
4. Workspace (connected by namespace)
5. Factory (connected by creator)
6. Recipe (connected by creator)
7. UserSShPair (connected by owner)
8. Stack (connected by creator)
9. Worker (connected by user and workspace)
10. Snapshots (no direct connection, via workspaces)
