### ISSUE TITLE
Study how to integrate with customers ldap

### ISSUE THREAD

**Issue by skabashnyuk** [codenvy/codenvy#399]
We need to figure out how to establish relationship between ldap entities such as User & Profile, and the rest of the entities.

**Comment by evoevodin** [comment]
Terminology:
- Primary storage: a storage used by Onpremises for storing all the data(like Workspaces, Preferences etc).
- Ldap storage:  customer's storage which is considered as read-only available storage that stores customer's organization Users and their Profiles
- Ldap cache: a copy of some of the User/Profile attributes from the Ldap storage in the Primary Storage.

Strategy:
- Synchronize data from the ldap storage to the ldap cache
  - Attributes:
    - Synchronization period - defines a time(in minutes probably) for performing the synchronization of users & profiles
    - Synchronization attributes - defines list of the attributes which will be synchronized. There are mandatory attributes like (id, name, email) and not-mandatory attributes like(firstName, lastName), all the mandatory attributes are the attributes of the User entity, all the non-mandatory attributes are
the attributes of the Profile entity. 
- Authenticate users using the Ldap storage. In this way we don't rely on the synchronization timing + we don't have to copy 'secure attributes'.
Due to this statement `UserDao` must be reworked and in the way to have a method which rather searches user by alias and password than makes authentication, 
so the Unauthorized exception should be removed from the method declaration and NotFoundException used instead. Nevertheless authentication must
be performed on the `UserManager` side, which basically should rethrow `NotFoundException` as `UnauthorizedException`.

This strategy allows to perform user dependent data aggregations on the primary storage, 
along with that all the user and profile data becomes  _Eventually Consistent_.

The implementation:
Synchronization should be performed by separate component, the component should be fail-fast and fail immediately when required attributes are missing or synchronization can't be performed.
Consider uSNChanged attribute for effective synchronization.
