### ISSUE TITLE
Prevent workspace starting if the system achieved resources limit.

### ISSUE THREAD

**Issue by vkuznyetsov** [codenvy/codenvy#408]
**Epic link** [(https://github.com/codenvy/codenvy/issues/406)]

If the system has achieved 90% of the allowed disk threshold OR 90% of total RAM available from all running workspaces, then the system:

1. Prevent any new workspaces from starting for any user. When doing this, we should print friendly error message to user before they attempt to start a workspace.
2. Have banner displayed to all users / admins indicating that the system is limiting new workspaces from running due to reaching max resources.

We need this to work properly for both UD-driven and factory-driven scenarios.

**Comment by TylerJewell** [comment]
@vkuznyetsov - please use markdown to format issues appropriately.  Markdown has bold, bullets, and numbering. The issue readability is important.  Also, paragraph spacing is important.

**Comment by vkuznyetsov** [comment]
![banneride](https://cloud.githubusercontent.com/assets/2101815/16950133/4a7989b0-4dc7-11e6-8604-8bf3f8f50dfb.png)
![bannerud](https://cloud.githubusercontent.com/assets/2101815/16950137/50e05568-4dc7-11e6-86a1-bd15737cd29e.png)
![notificationide](https://cloud.githubusercontent.com/assets/2101815/16950139/5333cc5a-4dc7-11e6-9604-c2df3df4e393.png)
![notificationud](https://cloud.githubusercontent.com/assets/2101815/16950141/5515b326-4dc7-11e6-8225-53ca055448ad.png)

**Comment by vinokurig** [comment]
Docker swarm does not provide any information about disc space of all nodes in the system, so only RAM usage will be checked.

**Comment by TylerJewell** [comment]
@vkuznyetsov do not merge this without a detailed UX review.  My first impressions was that there are grammar issues and formatting issues.

**Comment by TylerJewell** [comment]
Changes:
1: Will we be supporting multiple banners on the left if there are multiple system events?  It does not seem to be very scalable.  If we have 6 permanent alerts that we must provide to the user / admin, we cannot fit 6 left bar items.  We should consider having a thin bar on top of the UD + IDE area that spans the full width of left-to-right.

2: Permanent message should be.  "Low RAM".  The system is low on RAM. New workspaces will not start until more RAM is available."

3: Notification message.  "Low RAM." Your workspace cannot be started until the system has more RAM available."

**Comment by vinokurig** [comment]
Items 1 and 2 are related to https://github.com/codenvy/codenvy/issues/502.
As for item 3 We have common way to show in IDE errors related to starting workspace. It will be like this:
![low_ram](https://cloud.githubusercontent.com/assets/7668752/17367311/2ae0cc4e-5998-11e6-8817-5cccfc98f8ca.jpg)
In the dashboard it will be like this (without left notification, it is a part of #502 ):
![low_ram_dashboard](https://cloud.githubusercontent.com/assets/7668752/17367569/246b2804-5999-11e6-977c-9edc5d60d784.jpg)

@TylerJewell Do you agree with these notifications?

**Comment by ashumilova** [comment]
2 and 3 is clear. 
About n.1 have a question - has this banner to handle all permanent alerts, or we will add banner per alert on top?

**Comment by TylerJewell** [comment]
The notifications are clear for those users that initiate an action.
What about the permanent-notification?  Should we also have a banner across the top or bottom of the screen that indicates that the system has a resource issue and you may not be able to start new workspaces?

**Comment by ashumilova** [comment]
@TylerJewell , @slemeur I can prepare both variants for you to choose the appropriate one.

**Comment by TylerJewell** [comment]
I didn't see your original question.   We should probably have one banner for each permanent alert.

**Comment by ashumilova** [comment]
![warning_top](https://cloud.githubusercontent.com/assets/1611939/17400852/fd8dd942-5a52-11e6-9714-42e15182545d.png)

maybe we can provide user ability to close it? or those messages have to take less space of the application. Like message "Low RAM" in left navbar and details on hover and closable? 
As for me - on top takes much space

**Comment by TylerJewell** [comment]
I like the idea of letting a user close the message.

**Comment by slemeur** [comment]
If the system is going to display multiple notifications, I'm not convince the latest proposed version will provide a proper experience as it will create as many banners as notifications we could have.
The ability to close the warning message, is a good idea because it lets the user being able to continue using the product normally - the notification reported might not affect him directly and could be ignored in certain cases - so it would not necessarily need to be displayed all the time. 

We'd need a notification handling mechanism. We already have in place the notifications that are raised when the user is performing certain actions - or when the system is running into a certain state. 
Taking the "Low RAM" notification:
- When the state of system is getting low on RAM resources, we'd display the notification to the user.
- The notification would still be accessible from a notification menu
- When the user try to start a new workspace/machine, we'd raise again the notification (in the context)

We’d just need a way to display all the current (and still accurate) notifications. 

![notificationud-v2](https://cloud.githubusercontent.com/assets/1636769/17593048/da5457e8-5fe4-11e6-9fe1-d0f9dd6f082e.png)

I still want to display those notifications from the left navigation menu - as it is available from UD and IDE with a consistent way.

**Comment by bmicklea** [comment]
@ashumilova - will the user see a notification in the UD related to this?

**Comment by ashumilova** [comment]
yes, the related issue to show notification is here https://github.com/codenvy/codenvy/issues/502

**Comment by slemeur** [comment]
@ashumilova : For 4.7.0, we will not target the new UI mecanism for the system notifications. We will use the one that we currently have in place and iterate in order to provide the right experience #631.

Please just clarify what has been done with #502 and if it's not relevant anymore, let's close that issue and work on #631.

**Comment by TylerJewell** [comment]
Has a dependency on http://github.com/eclipse/che/issues/1787.

**Comment by bmicklea** [comment]
What's the status of this - it's been pending merge for 17 days...what's blocking the merge?

**Comment by bmicklea** [comment]
@vinokurig so this was merged into the 4.5 branch?

**Comment by vinokurig** [comment]
@bmicklea no, changed the milestone

**Comment by bmicklea** [comment]
Thanks Igor

**Comment by slemeur** [comment]
@vinokurig : Could you please cross link the associated PR? 
This issue is closed, while we don't know what was the PR.
