### ISSUE TITLE
codenvy config --hostname=${hostname} fails

### ISSUE THREAD

**Issue by eivantsov** [codenvy/codenvy#420]
```
codenvy> config --hostname=apptium
WARNING: automatic update of IM CLI client has been failed. See logs for details                                                                                        
{
"message" : "Command execution fail. Error: Can't execute command 'COUNTER=0\n  while true; do\n  sudo puppet cert list --all | grep '\"apptium\"' &>/dev/null\n  hasCertificate=$?\n  if [[ $hasCertificate == 0 ]]; then\n     sudo systemctl restart puppetmaster\n     break\n  fi\n  sleep 10\n  let COUNTER=COUNTER+1\n  if [[ $COUNTER -eq 30 ]]; then\n     echo 'Puppet agent error' >&2\n     exit 1\n  fi\ndone\n'. Output: ; Error: Puppet agent error.",
"status" : "ERROR"
}
```

**Comment by dmytro-ndp** [comment]
It seems command was executed inside the codenvy installation manager install directory. Please, try to execute it again outside codenvy directory. 
If it doesn't help, review of
/var/log/puppet/puppet-agent.log and codenvy/cli/logs/cli.log would be useful.

**Comment by TylerJewell** [comment]
Also dymtro.  Please change the error message from "has been failed" to "failed".  Better English.

**Comment by eivantsov** [comment]
@tolusha can you verify @dmytro-ndp's suggestion helps?

**Comment by tolusha** [comment]
I didn't help.

`Caused by: com.codenvy.im.agent.AgentException: Can't execute command 'COUNTER=0
  while true; do
  sudo puppet cert list --all | grep '"codenvy"' &>/dev/null
  hasCertificate=$?
  if [[ $hasCertificate == 0 ]]; then
     sudo systemctl restart puppetmaster
     break
  fi
  sleep 10
  let COUNTER=COUNTER+1
  if [[ $COUNTER -eq 30 ]]; then
     echo 'Puppet agent error' >&2
     exit 1
  fi
done
'. Output: ; Error: Puppet agent error.
<------>at com.codenvy.im.agent.AgentException.create(AgentException.java:34)
<------>at com.codenvy.im.agent.LocalAgent.executeWithoutPassword(LocalAgent.java:97)
<------>at com.codenvy.im.agent.LocalAgent.execute(LocalAgent.java:54)
<------>at com.codenvy.im.commands.SimpleCommand.execute(SimpleCommand.java:104)
<------>... 27 more
Caused by: java.lang.Exception: Output: ; Error: Puppet agent error.
<------>at com.codenvy.im.agent.AbstractAgent.processOutput(AbstractAgent.java:53)
<------>at com.codenvy.im.agent.LocalAgent.executeWithoutPassword(LocalAgent.java:94)
<------>... 29 more
.
2016-07-20 14:56:05 +0100 [SEVERE] com.codenvy.im.console.Console printErrorAndExit {
  "message" : "Command execution fail. Error: Can't execute command 'COUNTER=0\n  while true; do\n  sudo puppet cert list --all | grep '\"codenvy\"' &>/dev/null\n  hasCertificate=$?\n  if [[ $hasCertificate == 0
  "status" : "ERROR"
}..
`

**Comment by tolusha** [comment]
Puppet agent log:
2016-07-20 14:40:55 +0100 Puppet (notice): Finished catalog run in 4.62 seconds
2016-07-20 14:43:44 +0100 Puppet (notice): Caught TERM; exiting
2016-07-20 14:50:09 +0100 Puppet (err): Could not request certificate: Connection timed out - connect(2)
2016-07-20 14:50:30 +0100 Puppet (err): Could not run: SIGTERM
2016-07-20 14:56:53 +0100 Puppet (err): Could not request certificate: Connection timed out - connect(2)

**Comment by bmicklea** [comment]
Removing blocker status because this does not require changes to code so can be released at any time.

**Comment by dmytro-ndp** [comment]
I reproduced this issue locally in case when IP of 'apptium' host is unavailable.
_Fixup_: add next record into **/etc/hosts** file on _Master Server_:
```127.0.0.1 apptium```

Actually, there is dedicated issue #464 to do such kind of fixup automatically.
