### ISSUE TITLE
Shared workspace doesn't refresh automatically

### ISSUE THREAD

**Issue by ishepard** [codenvy/codenvy#422]
Hi,
I created a workspace shared with a friend and inside I put the "console-java-simple" project.

Then I modified a file (added a println), and what happened is that:

- my friend doesn't see the file modified, but the older version
- it he builds&runs the project he has the output of newer version!

So, I think that the problem is just refreshing the file explorer. Is there any button to do that?

**Comment by TylerJewell** [comment]
In the project explorer, there is a little refresh button that a user can hit to see the updated changes to the tree.  This will become automatic once this issue is resolve.  This issue is in Che and it will allow the server to notify browsers when changes are made by outsiders - so not refresh required.

https://github.com/eclipse/che/issues/1824

**Comment by ishepard** [comment]
Thank you for your reply @TylerJewell.
However the problem still exists. That button works only if a new file is created (it refreshes only the project tree). But if I modify a file the other guy will not see the change, which could be not a problem except that when he runs the project he actually runs the newer version.

**Comment by TylerJewell** [comment]
The refresh button refreshes the project tree.  I believe you have to close the file and reopen it right now for the user to see the changes.  Once the notification issue is resolved in the next couple of sprints, then the editor will be updated automatically as well.

**Comment by ishepard** [comment]
Yes if I close and re-open it works. Thank you
