### ISSUE TITLE
Problem Deploying to GAE

### ISSUE THREAD

**Issue by jcoonrod** [codenvy/codenvy#428]
Authentication process to deploy to GAE is extremely burdensome (unlike with codenvy 3, where it was built in). The only way to do it is manually from the terminal - which requires cutting and pasting  a long authentication string to the browser - then cutting and pasting the authentication code back again. (And then - today - ctrl-C copy has stopped working so it cannot work at all.) 

Every startup of codenvy creates a new machine name - which is passed to gae as part of the authentication - which means there is no way to save credentials in a file.

We would like a plugin that will automate the authentication process.

**Comment by eivantsov** [comment]
Porting GAE plugin from v3 would be a proper solution here.

**Comment by jcoonrod** [comment]
How can I make this happen?

**Comment by eivantsov** [comment]
@jcoonrod this is smth for product management to priority this issue and backport GAE plugin from 3 to 4 version.
@TylerJewell @slemeur can say more.

**Comment by aurena** [comment]
Has there been an update to this?  I too find deploying to GAE via Codenvy 4 extremely frustrating.  I can't even find clear simple instructions on how to do this the hard way.  Running the update command from the terminal just gives me --noauth_local_webserver.
Any information would be appreciated.
Thanks

**Comment by TylerJewell** [comment]
We do not have any plans to port the GAE plugin from Codenvy 3 to Codenvy 4 at this time. We have added documentation to the Eclipse Che docs on how to install the GAE client and how to use it in the terminal on the command line.  We have these docs in Eclipse Che.

@JamesDrummond - please add a review of these docs to the PM tracking list.
https://eclipse-che.readme.io/docs/che-and-gae

Thinks that should be evaluated:
1. How to install GAE library into a stack.
2. Examples for Java, PHP, Python
3. Clean up hte text boxes so that comments and commands do not break and wrap.
4. Add in syntax highlighting by configuring the code boxes.
