### ISSUE TITLE
Support of AWS ECR dynamic passwords

### ISSUE THREAD

**Issue by skabashnyuk** [codenvy/codenvy#453]
Now password for private docker registry is static value in configuration.
But in AWS ECR it's changed once in x hours. We need to find a way how better handle 
AWS ECR dynamic passwords.
Options
- parse output of `aws get-login` command
- Find AWS API to get this value.

Related to https://github.com/codenvy/codenvy/issues/444

**Comment by bmicklea** [comment]
@skabashnyuk: This is affecting a customer - assess and add a status label, this is urgent.

**Comment by skabashnyuk** [comment]
@vkuznyetsov  please manage it in your sprint plans as needed.

**Comment by bmicklea** [comment]
The team has investigated AWS ECR and believe that the best implementation would be:
1. To store 4 properties in Codenvy: account ID, ECR region, secret key ID, secret key.
2. On each pull/push/build we use the AWS Java client to get the ECR token using the 4 properties above.
3. We send the retrieved token to the Docker daemon so it's able to pull/push/build.

Since we're doing this for each operation the key rollover won't affect us.

@soanni: Do you use only 1 AWS registry in 1 account and 1 region?

**Comment by soanni** [comment]
@bmicklea no we have multiple accounts i believe. I need to check it with Matias. I will come back with the answer.

**Comment by soanni** [comment]
@bmicklea we have multiple registries in multiple accounts. 
I can imagine this workflow (of course i don't know is that possible and how much effort it will need to develop).
1. When I as administrator create the workspace i can select somewhere in the GUI the account (for example: aurea, devfactory, crossover), the registry.
2. Then i can use images from that account in JSON objects when i'm creating a workspace OR in future docker-compose YAML configurations
3. This account/registry will be linked to that workspace and every start of the workspace will trigger docker login to that account.

In order to do this for sure we should find a way to store multiple secret keys/secret ids for multiple accounts.

P.S. I also can suggest showing the list of images somewhere in the workspace creation form that are stored in the selected account/registry.
Of course this is just my humble opinion..

**Comment by bmicklea** [comment]
@soanni: Due to the urgency of this request we are trying to keep the scope limited to only what's absolutely needed for now. Once we have this ECR integration complete you can create a new enhancement request issue outlining the further capabilities you'd like to see.

**Comment by garagatyi** [comment]
@soanni Can you, please, describe more about your use-case. Are you using registries as mirrors or as standalone units? 
Can you provide the example of your configuration:
- accounts
- registries of these accounts
- repository of images you are using in FROM directive of dockerfiles

You can change real IDs, but, please keep them synchronized if registries/accounts shares them.
This information will be very helpful to implement easy to use and secure solution.

**Comment by soanni** [comment]
@garagatyi @bmicklea i will write an email to Brad and will describe our mechanics. Just don't want to make this info public here

**Comment by mmorhun** [comment]
Done.
To create workspace from image which is stored in AWS ECR, configure following properties:
```

**Comment by mmorhun** [comment]
Done.
To create workspace from image which is stored in AWS ECR, configure following properties:
```
docker.registry.aws.id=
docker.registry.aws.region=
docker.registry.aws.access-key-id=
docker.registry.aws.secret-access-key=
```
When new properties are applied, you can create your workspace using recipe.
The simplest recipe is:
```
FROM <your_aws_id>.dkr.ecr.<your_aws_region>.amazonaws.com/<your_image>[:tag]
```
