### ISSUE TITLE
Check if workspace backup performed on docker service restart or stop

### ISSUE THREAD

**Issue by vinokurig** [codenvy/codenvy#482]
**Expected behavior:**
Workspace backup must be always performed on docker service restart or stop

**Comment by vkuznyetsov** [comment]
Now if for some reason we need to stop or restart docker service on MachineNode it stops containers.
When API detects that machine isn't running it simply deletes machines. This way we are losing file changes made after previous scheduled backup.

Need to check whether a system makes WS backup before deleting machine on docker service restart or stop

**Comment by AndrienkoAleksandr** [comment]
We don't do backUp workspace on stop or restart docker service. We can fix situation with "service docker stop", because in this case we will get event from docker swarm connector "engine_disconnect", so we can handle this event and backup workspaces (but technical design won't be clear, it's will be some hack). And if we do "stop" and "start" of the "docker service" very quickly then docker swarm can won't throw "engine_disconnect" event, because swarm throw event only if node is not accessible for some period of time. For "docker service restart" we can't do anything, because docker swarm connector does not throw any events in this case. I suggest wait docker api 1.12. In api 1.12 we can use docker swarm mode. Maybe in this version api we will get new possibility to handle "stop" and "restart" docker service.
