### ISSUE TITLE
Snapshot restore not happening

### ISSUE THREAD

**Issue by codec-abc** [codenvy/codenvy#492]
Hi, 

I ran into an issue when trying to restore some snapshot. Snapshots seem to be created but I don't get the popup to restore the snapshot each time I reload the workspace. It happen sometimes but not always.

The problem can be reproduced with the following :

- Start with a blank workspace
- Install some depedencies (for example install nano `sudo apt-get update && sudo apt-get install nano` )
- Create a snapshot
- Stop the workspace
- Run the workspace

Then at this point if you are lucky you will have a popup (like the following one) asking you if you want to restore the snapshot
![like this one](https://www.geeketfier.fr/images/eclipse_che_recover_snapshot.png). 

If I click yes everything work as expected.
But the problem is that in most of the time I don't get the popup and it just start like a fresh workspace and the dependencies are lost (If I installed nano and type `nano` I get `nano : command not found`). So I need to install the dependencies once again manually.

**Comment by TylerJewell** [comment]
@codec-abc - could the issue be related to this one.  I am wondering if the snapshot is unfinished before actions to stop the workspace are being taken.
https://github.com/eclipse/che/issues/1849

**Comment by codec-abc** [comment]
Maybe, don't know how to test that. And what is supposed to happen if I restart a workspace while creating a snapshot ? By the way, is there any way to see snapshots associated to a workspace ?

**Comment by TylerJewell** [comment]
We should prevent you from stopping and restarting a workspace if we are in the middle of a snapshot. And if you hard kill the server in the middle of a snapshot operation, it's expected for the system to gracefully recover and rebuild the workspace from the default recipe + project git operation.  If neither of those things happen and / or you have a valid snapshot and it's not recoverable, then it's a system failure and we need to diagnose the root cause + solve it.

Right now, we have a 1:1 relationship between workspaces and snapshots. They are quite large so we just rotate through them. You'd know that you have a snapshot by doing `docker images` and you will see an image that was created by Che on your system. You may have different images there for different workspaces.

**Comment by eivantsov** [comment]
@codec-abc can you elaborate on what `most of the time` means?

I have just snapshotted a few workspaces - no issues. The thing is that if you start a workspace, snapshot it, stop and start again you will always see a popup with a prompt. However, if you start it from a snapshot and just stop, you will start from a fresh workspace next time. So, you should snapshot your workspace every time you stop it or configure Che to do this for you.

By the way, this is the wrong project to create an issue. Next time, please go to https://github.com/eclipse/che/issues.

**Comment by codec-abc** [comment]
Well it is working now on my workspace. I wonder if it is not a delay thing. Like if you make a snapshot and stop and run the workspace right away the popup does not appear. By the way, is codenvy configured to auto-snapshot workspace ?
And regarding the issue being posted on the wrong project please excuse me for that but note that the [codenvy support page](https://codenvy.com/support/) redirect here

**Comment by eivantsov** [comment]
Are we talking about Che or Codenvy? In Che you can configure auto snapshots. Codenvy, does not auto snapshot stopped workspaces.
