### ISSUE TITLE
Log data when user access a workspace

### ISSUE THREAD

**Issue by tolusha** [codenvy/codenvy#638]
Write to log file each time when user access a workspace. Log file should be located near the tomcat access log.

Log data:
- access timestamp in  some universal format.
- user name
- workspace id 
- workspace name

Trigger:
- User request a workspace by @GET  'api/workspace` method

**Comment by tolusha** [comment]
@bmicklea @TylerJewell any requirements or we can postpone these issue?

**Comment by TylerJewell** [comment]
Ok for me

**Comment by tolusha** [comment]
> What kind of info to log
accessTime userId workspaceId permissions

> What triggers should initiate logging
`api/workspace/get` method

**Comment by TylerJewell** [comment]
I think you are assuming that this is logging access through the Codenvy server.  But I think that this would need to be any time that someone accesses the workspace directly.  Since we do not proxy all user traffic through the Codenvy server, wouldn't this need to be something in the ws agent that logs the access back to the codenvy core?

The access would be any time someone does something that causes one of our agents to be accessed on the workspace.  The agent would then log an agent access back with Codenvy for the user.

accessTime would be day / time in some universal format.
userid would be the username (pretty format) so tylerjewell@gmail.com if an email address
workspaceid would be the workspace id + workspace pretty name

Permissions would not be part of this logging.  In the other issue where we display the permissions that a user has for each workspace they are a member of, then we would show their permission type there.  This issue is specifically about when a user accesses a workspace.

**Comment by tolusha** [comment]
No Codenvy server. Ws master will log data once user request a workspace.

**Comment by TylerJewell** [comment]
We need to assume that every access a user makes to any agent in a ws, will need to be logged as access in codenvy master.

**Comment by tolusha** [comment]
Do you mean ws-agent/terminal? anything else?

**Comment by TylerJewell** [comment]
Yes, fair question.  I think ws-agent and terminal agent - those two make sense.

**Comment by tolusha** [comment]
Logging access to the terminal - an issue. Can't be solved quickly.

**Comment by TylerJewell** [comment]
Ok to defer that.  Just handle ws-agent access initially.

**Comment by tolusha** [comment]
I've updated the description.

**Comment by TylerJewell** [comment]
@slemeur @bmicklea - do we think this is still useful in a k8s world?

**Comment by bmicklea** [comment]
up to @slemeur but I would assume the logging in k8s would be a decent start.

**Comment by eivantsov** [comment]
This issue was moved to eclipse/che#5659
