### ISSUE TITLE
Cannot create workspace from the JAVA-MYSQL stack

### ISSUE THREAD

**Issue by musienko-maxim** [codenvy/codenvy#806]
**Reproduction Steps:**
Go to the Dashboard and try to create workspace from JAVA-MYSQL ready to go stack.

**Expected behavior:**
The workspace should be created without errors.
**Observed behavior:**
We have problem like screenshot: 
![selection_014](https://cloud.githubusercontent.com/assets/1640058/18710243/dc60e568-800c-11e6-8f9a-2a5a4ed5231c.png)

**Codenvy version:** [Enter Codenvy version here]
**OS and version:** [Enter OS name and version here]

Codenvy version: 5.0.0-M1
OS and version: Ubuntu 14.04 LTS
Chrome-browser

**Comment by mmorhun** [comment]
Already fixed by eivantsov

**Comment by garagatyi** [comment]
it was workarounded, not fixed

**Comment by JamesDrummond** [comment]
Unless we want to eventually change our stack to have `links` instead of `depends_on` I think this issue can be closed. I created a new issue specific for resolving `links`. [https://github.com/eclipse/che/issues/2687](https://github.com/eclipse/che/issues/2687).

See additional information for why `depends_on` can be used instead of `links` at [http://stackoverflow.com/questions/35832095/difference-between-links-and-depends-on-in-docker-compose-yml](http://stackoverflow.com/questions/35832095/difference-between-links-and-depends-on-in-docker-compose-yml). However we should still support `links`.

**Comment by vkuznyetsov** [comment]
depends on https://github.com/eclipse/che/issues/2687

**Comment by TylerJewell** [comment]
@garagatyi - please rename the issue to be clear on problem.  The stack technically works, so if this is an improvement, then we need to state what is being improved.

**Comment by garagatyi** [comment]
We now have another issue that tracks actual problem, so I'm closing this issue
