### ISSUE TITLE
UI does not accurately represent workspace snapshot state

### ISSUE THREAD

**Issue by bmicklea** [codenvy/codenvy#931]
If you snapshot a workspace on beta.codenvy.com (5.0 M5), the left navigation bar during snapshoting says the workspace is offline (gray dot). However, after the snapshot is completed, the workspace is still running.  So the dot is incorrect - we have a left nav that thinks the ws is offline when it is still online.  Going into other parts of our product, UD thinks the workpace is offline and will not let me start it.  But if I go into the IDE the workspace is running.

**Expected behavior:**
UI accurately reflects the state of the snapshot operation and the states of the workspace.

**Observed behavior:**
UI does not match workspace / snapshot state.

**Codenvy version:** 5.0.0-M5
**OS and version:** beta.codenvy.com

**Comment by slemeur** [comment]
Please @ashumilova + @olexii4 give a look on this issue.

**Comment by bmicklea** [comment]
I believe this is resolved by fixing #933

**Comment by slemeur** [comment]
The problem is that the server is sending an event to notify the "start_snaphot". This event might be missed from the UD and the server is not sending the state "snapshotting" when getting the list of workspaces.

Actions:
- Plugin team : put the gray icon in "orange" when the snapshot is in progress.
- Platform team : @skabashnyuk We need the api to retrieve the list of workspaces, providing the "snapshotting" state

**Comment by slemeur** [comment]
Cross link with: https://github.com/eclipse/che/issues/2683
