### ISSUE TITLE
Cannot interact with console application

### ISSUE THREAD

**Issue by fultonm** [codenvy/codenvy#984]
I cannot give input to my console application

**Reproduction Steps:**

Create a simple console application to accept user input with Scanner.nextLine() and run it.

**Expected behavior:**

Codeenvy IDE will accept input directly in the console where the program's output is displayed.

**Observed behavior:**

Codeenvy IDE does not accept input directly in the console where the program's output is displayed.

**Codenvy version:** 5.0.0-M5
**OS and version:** Windows 10 14946.1000

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy: [Yes / **No**]
Problem can be reliably reproduced: [**Yes** / No - it's random]

**Diagnostic bundle**
Execute the script on [this page](https://github.com/codenvy/codenvy/wiki/Support-Diagnostics) and post public link to the bundle here.

https://gist.github.com/fultonm/9689ee62a494434751c7a3322ff473d4

**Comment by TylerJewell** [comment]
Hi @fultonm - if you would like to have input for your program, you need to execute the program directly in the terminal.  We don't support commands that have user input, yet due to limitations in Eclipse Che.  There are some open github issues that are tracking work that we would need to do to enable commands to either be parameterized or inputs for a future release.

**Comment by fultonm** [comment]
As a student trying to embrace next gen IDE paradigms this is making it hard 😂
